<?php

return [
    'colors' => [
        'beartropy' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-beartropy-100 text-beartropy-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-beartropy-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-beartropy-900',
            'slot' => 'text-beartropy-800 leading-normal',
            'icon' => '',
        ],
        'success' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-green-100 text-green-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-green-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-green-900',
            'slot' => 'text-green-800 leading-normal',
            'icon' => '',
        ],
        'info' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-blue-100 text-blue-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-blue-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-blue-900',
            'slot' => 'text-blue-800 leading-normal',
            'icon' => '',
        ],
        'warning' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-yellow-100 text-yellow-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-yellow-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-yellow-900',
            'slot' => 'text-yellow-800 leading-normal',
            'icon' => '',
        ],
        'error' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-red-100 text-red-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-red-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-red-900',
            'slot' => 'text-red-800 leading-normal',
            'icon' => '',
        ],
        'red' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-red-100 text-red-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-red-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-red-900',
            'slot' => 'text-red-800 leading-normal',
            'icon' => '',
        ],
        'blue' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-blue-100 text-blue-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-blue-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-blue-900',
            'slot' => 'text-blue-800 leading-normal',
            'icon' => '',
        ],
        'green' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-green-100 text-green-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-green-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-green-900',
            'slot' => 'text-green-800 leading-normal',
            'icon' => '',
        ],
        'yellow' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-yellow-100 text-yellow-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-yellow-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-yellow-900',
            'slot' => 'text-yellow-800 leading-normal',
            'icon' => '',
        ],
        'purple' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-purple-100 text-purple-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-purple-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-purple-900',
            'slot' => 'text-purple-800 leading-normal',
            'icon' => '',
        ],
        'pink' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-pink-100 text-pink-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-pink-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-pink-900',
            'slot' => 'text-pink-800 leading-normal',
            'icon' => '',
        ],
        'gray' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-gray-100 text-gray-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-gray-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-gray-900',
            'slot' => 'text-gray-800 leading-normal',
            'icon' => '',
        ],
        'orange' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-orange-100 text-orange-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-orange-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-orange-900',
            'slot' => 'text-orange-800 leading-normal',
            'icon' => '',
        ],
        'amber' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-amber-100 text-amber-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-amber-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-amber-900',
            'slot' => 'text-amber-800 leading-normal',
            'icon' => '',
        ],
        'lime' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-lime-100 text-lime-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-lime-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-lime-900',
            'slot' => 'text-lime-800 leading-normal',
            'icon' => '',
        ],
        'emerald' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-emerald-100 text-emerald-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-emerald-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-emerald-900',
            'slot' => 'text-emerald-800 leading-normal',
            'icon' => '',
        ],
        'teal' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-teal-100 text-teal-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-teal-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-teal-900',
            'slot' => 'text-teal-800 leading-normal',
            'icon' => '',
        ],
        'cyan' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-cyan-100 text-cyan-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-cyan-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-cyan-900',
            'slot' => 'text-cyan-800 leading-normal',
            'icon' => '',
        ],
        'sky' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-sky-100 text-sky-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-sky-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-sky-900',
            'slot' => 'text-sky-800 leading-normal',
            'icon' => '',
        ],
        'indigo' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-indigo-100 text-indigo-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-indigo-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-indigo-900',
            'slot' => 'text-indigo-800 leading-normal',
            'icon' => '',
        ],
        'violet' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-violet-100 text-violet-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-violet-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-violet-900',
            'slot' => 'text-violet-800 leading-normal',
            'icon' => '',
        ],
        'rose' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-rose-100 text-rose-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-rose-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-rose-900',
            'slot' => 'text-rose-800 leading-normal',
            'icon' => '',
        ],
        'fuchsia' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-fuchsia-100 text-fuchsia-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-fuchsia-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-fuchsia-900',
            'slot' => 'text-fuchsia-800 leading-normal',
            'icon' => '',
        ],
        'slate' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-slate-100 text-slate-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-slate-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-slate-900',
            'slot' => 'text-slate-800 leading-normal',
            'icon' => '',
        ],
        'stone' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-stone-100 text-stone-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-stone-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-stone-900',
            'slot' => 'text-stone-800 leading-normal',
            'icon' => '',
        ],
        'zinc' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-zinc-100 text-zinc-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-zinc-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-zinc-900',
            'slot' => 'text-zinc-800 leading-normal',
            'icon' => '',
        ],
        'neutral' => [
            'main' => 'flex items-start gap-3 p-4 rounded-lg shadow bg-neutral-100 text-neutral-900',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'text-neutral-600 flex-shrink-0',
            'icon_class' => 'w-7 h-7',
            'title' => 'font-bold mb-1 text-lg leading-tight text-neutral-900',
            'slot' => 'text-neutral-800 leading-normal',
            'icon' => '',
        ],
    ],
];
