<?php

return [
    'colors' => [
        'beartropy' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-beartropy-50 text-beartropy-800 border-beartropy-300 dark:bg-gray-900 dark:text-beartropy-300 dark:border-beartropy-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'success' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-green-50 text-green-800 border-green-300 dark:bg-gray-900 dark:text-green-300 dark:border-green-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight ',
            'slot' => 'leading-normal',
            'icon' => 'check-circle',
        ],
        'info' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow text-blue-800 bg-blue-50 border-blue-300 dark:bg-gray-900 dark:text-blue-300 dark:border-blue-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => 'exclamation-circle',
        ],
        'warning' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow text-yellow-800 bg-yellow-50 border-yellow-300 dark:bg-gray-900 dark:text-yellow-300 dark:border-yellow-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => 'exclamation-triangle',
        ],
        'error' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow text-red-800 bg-red-50 border-red-300 dark:bg-gray-900 dark:text-red-300 dark:border-red-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => 'x-circle',
        ],
        'red' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-red-50 text-red-800 border-red-300 dark:bg-gray-900 dark:text-red-300 dark:border-red-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'blue' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-blue-50 text-blue-800 border-blue-300 dark:bg-gray-900 dark:text-blue-300 dark:border-blue-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'green' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-green-50 text-green-800 border-green-300 dark:bg-gray-900 dark:text-green-300 dark:border-green-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'yellow' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-yellow-50 text-yellow-800 border-yellow-300 dark:bg-gray-900 dark:text-yellow-300 dark:border-yellow-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'purple' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-purple-50 text-purple-800 border-purple-300 dark:bg-gray-900 dark:text-purple-300 dark:border-purple-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'pink' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-pink-50 text-pink-800 border-pink-300 dark:bg-gray-900 dark:text-pink-300 dark:border-pink-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'gray' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-gray-50 text-gray-800 border-gray-300 dark:bg-gray-900 dark:text-gray-300 dark:border-gray-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'orange' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-orange-50 text-orange-800 border-orange-300 dark:bg-gray-900 dark:text-orange-300 dark:border-orange-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'amber' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-amber-50 text-amber-800 border-amber-300 dark:bg-gray-900 dark:text-amber-300 dark:border-amber-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'lime' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-lime-50 text-lime-800 border-lime-300 dark:bg-gray-900 dark:text-lime-300 dark:border-lime-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'emerald' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-emerald-50 text-emerald-800 border-emerald-300 dark:bg-gray-900 dark:text-emerald-300 dark:border-emerald-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'teal' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-teal-50 text-teal-800 border-teal-300 dark:bg-gray-900 dark:text-teal-300 dark:border-teal-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'cyan' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-cyan-50 text-cyan-800 border-cyan-300 dark:bg-gray-900 dark:text-cyan-300 dark:border-cyan-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'sky' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-sky-50 text-sky-800 border-sky-300 dark:bg-gray-900 dark:text-sky-300 dark:border-sky-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'indigo' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-indigo-50 text-indigo-800 border-indigo-300 dark:bg-gray-900 dark:text-indigo-300 dark:border-indigo-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'violet' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-violet-50 text-violet-800 border-violet-300 dark:bg-gray-900 dark:text-violet-300 dark:border-violet-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'rose' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-rose-50 text-rose-800 border-rose-300 dark:bg-gray-900 dark:text-rose-300 dark:border-rose-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'fuchsia' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-fuchsia-50 text-fuchsia-800 border-fuchsia-300 dark:bg-gray-900 dark:text-fuchsia-300 dark:border-fuchsia-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'slate' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-slate-50 text-slate-800 border-slate-300 dark:bg-gray-900 dark:text-slate-300 dark:border-slate-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'stone' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-stone-50 text-stone-800 border-stone-300 dark:bg-gray-900 dark:text-stone-300 dark:border-stone-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'zinc' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-zinc-50 text-zinc-800 border-zinc-300 dark:bg-gray-900 dark:text-zinc-300 dark:border-zinc-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
        'neutral' => [
            'main' => 'flex items-start gap-3 p-4 border rounded-lg shadow bg-neutral-50 text-neutral-800 border-neutral-300 dark:bg-gray-900 dark:text-neutral-300 dark:border-neutral-800',
            'content' => 'flex-1 min-w-0',
            'icon_wrapper' => 'flex-shrink-0 me-3',
            'icon_class' => '!w-14 !h-14',
            'title' => 'font-bold mb-1 text-lg leading-tight',
            'slot' => 'leading-normal',
            'icon' => '',
        ],
    ],
];
