<?php

return [
    'colors' => [
        'beartropy' => [
            'bg' => 'bg-beartropy-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'red' => [
            'bg' => 'bg-red-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'blue' => [
            'bg' => 'bg-blue-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'green' => [
            'bg' => 'bg-green-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'yellow' => [
            'bg' => 'bg-yellow-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'purple' => [
            'bg' => 'bg-purple-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'pink' => [
            'bg' => 'bg-pink-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'gray' => [
            'bg' => 'bg-gray-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'orange' => [
            'bg' => 'bg-orange-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'amber' => [
            'bg' => 'bg-amber-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'lime' => [
            'bg' => 'bg-lime-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'emerald' => [
            'bg' => 'bg-emerald-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'teal' => [
            'bg' => 'bg-teal-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'cyan' => [
            'bg' => 'bg-cyan-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'sky' => [
            'bg' => 'bg-sky-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'indigo' => [
            'bg' => 'bg-indigo-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'violet' => [
            'bg' => 'bg-violet-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'rose' => [
            'bg' => 'bg-rose-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'fuchsia' => [
            'bg' => 'bg-fuchsia-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'slate' => [
            'bg' => 'bg-slate-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'stone' => [
            'bg' => 'bg-stone-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'zinc' => [
            'bg' => 'bg-zinc-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
        'neutral' => [
            'bg' => 'bg-neutral-600',
            'text' => 'text-white',
            'border' => 'border border-neutral-300 dark:border-neutral-700',
            'ring' => '',
            'font' => 'font-bold',
        ],
    ],
];
