<?php

return [
    'colors' => [
        'solid' => [
            'beartropy' => [
                'bg' => 'bg-beartropy-600 dark:bg-beartropy-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-beartropy-700 hover:shadow-md dark:hover:bg-beartropy-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-beartropy-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-beartropy-800 active:shadow-none dark:active:bg-beartropy-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'red' => [
                'bg' => 'bg-red-600 dark:bg-red-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-red-700 hover:shadow-md dark:hover:bg-red-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-red-800 active:shadow-none dark:active:bg-red-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'blue' => [
                'bg' => 'bg-blue-600 dark:bg-blue-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-blue-700 hover:shadow-md dark:hover:bg-blue-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-blue-800 active:shadow-none dark:active:bg-blue-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'green' => [
                'bg' => 'bg-green-600 dark:bg-green-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-green-700 hover:shadow-md dark:hover:bg-green-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-green-800 active:shadow-none dark:active:bg-green-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'yellow' => [
                'bg' => 'bg-yellow-400 dark:bg-yellow-300',
                'text' => 'text-neutral-900',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-yellow-500 hover:shadow-md dark:hover:bg-yellow-200',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-yellow-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-yellow-600 active:shadow-none dark:active:bg-yellow-400',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'purple' => [
                'bg' => 'bg-purple-600 dark:bg-purple-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-purple-700 hover:shadow-md dark:hover:bg-purple-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-purple-800 active:shadow-none dark:active:bg-purple-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'pink' => [
                'bg' => 'bg-pink-600 dark:bg-pink-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-pink-700 hover:shadow-md dark:hover:bg-pink-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pink-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-pink-800 active:shadow-none dark:active:bg-pink-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'gray' => [
                'bg' => 'bg-gray-600 dark:bg-gray-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-gray-700 hover:shadow-md dark:hover:bg-gray-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-gray-800 active:shadow-none dark:active:bg-gray-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'orange' => [
                'bg' => 'bg-orange-500 dark:bg-orange-400',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-orange-600 hover:shadow-md dark:hover:bg-orange-300',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-orange-700 active:shadow-none dark:active:bg-orange-500',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'amber' => [
                'bg' => 'bg-amber-500 dark:bg-amber-400',
                'text' => 'text-neutral-900',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-amber-600 hover:shadow-md dark:hover:bg-amber-300',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-amber-700 active:shadow-none dark:active:bg-amber-500',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'lime' => [
                'bg' => 'bg-lime-500 dark:bg-lime-400',
                'text' => 'text-neutral-900',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-lime-600 hover:shadow-md dark:hover:bg-lime-300',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lime-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-lime-700 active:shadow-none dark:active:bg-lime-500',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'emerald' => [
                'bg' => 'bg-emerald-600 dark:bg-emerald-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-emerald-700 hover:shadow-md dark:hover:bg-emerald-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-emerald-800 active:shadow-none dark:active:bg-emerald-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'teal' => [
                'bg' => 'bg-teal-600 dark:bg-teal-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-teal-700 hover:shadow-md dark:hover:bg-teal-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-teal-800 active:shadow-none dark:active:bg-teal-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'cyan' => [
                'bg' => 'bg-cyan-500 dark:bg-cyan-400',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-cyan-600 hover:shadow-md dark:hover:bg-cyan-300',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-cyan-700 active:shadow-none dark:active:bg-cyan-500',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'sky' => [
                'bg' => 'bg-sky-500 dark:bg-sky-400',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-sky-600 hover:shadow-md dark:hover:bg-sky-300',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-sky-700 active:shadow-none dark:active:bg-sky-500',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'indigo' => [
                'bg' => 'bg-indigo-600 dark:bg-indigo-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-indigo-700 hover:shadow-md dark:hover:bg-indigo-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-indigo-800 active:shadow-none dark:active:bg-indigo-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'violet' => [
                'bg' => 'bg-violet-600 dark:bg-violet-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-violet-700 hover:shadow-md dark:hover:bg-violet-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-violet-800 active:shadow-none dark:active:bg-violet-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'rose' => [
                'bg' => 'bg-rose-600 dark:bg-rose-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-rose-700 hover:shadow-md dark:hover:bg-rose-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-rose-800 active:shadow-none dark:active:bg-rose-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'fuchsia' => [
                'bg' => 'bg-fuchsia-600 dark:bg-fuchsia-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-fuchsia-700 hover:shadow-md dark:hover:bg-fuchsia-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-fuchsia-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-fuchsia-800 active:shadow-none dark:active:bg-fuchsia-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'slate' => [
                'bg' => 'bg-slate-600 dark:bg-slate-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-slate-700 hover:shadow-md dark:hover:bg-slate-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-slate-800 active:shadow-none dark:active:bg-slate-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'stone' => [
                'bg' => 'bg-stone-600 dark:bg-stone-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-stone-700 hover:shadow-md dark:hover:bg-stone-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-stone-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-stone-800 active:shadow-none dark:active:bg-stone-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'zinc' => [
                'bg' => 'bg-zinc-600 dark:bg-zinc-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-zinc-700 hover:shadow-md dark:hover:bg-zinc-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-zinc-800 active:shadow-none dark:active:bg-zinc-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'neutral' => [
                'bg' => 'bg-neutral-600 dark:bg-neutral-500',
                'text' => 'text-white',
                'border' => 'border-transparent shadow-sm dark:shadow-none',
                'hover' => 'hover:bg-neutral-700 hover:shadow-md dark:hover:bg-neutral-400',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:bg-neutral-800 active:shadow-none dark:active:bg-neutral-600',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
        ],

        'soft' => [
            'beartropy' => [
                'bg' => 'bg-beartropy-50 dark:bg-beartropy-950/50',
                'text' => 'text-beartropy-700 dark:text-beartropy-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-beartropy-100 dark:hover:bg-beartropy-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-beartropy-400 dark:focus-visible:ring-beartropy-500',
                'active' => 'active:bg-beartropy-200 dark:active:bg-beartropy-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'red' => [
                'bg' => 'bg-red-50 dark:bg-red-950/50',
                'text' => 'text-red-700 dark:text-red-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-red-100 dark:hover:bg-red-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-400 dark:focus-visible:ring-red-500',
                'active' => 'active:bg-red-200 dark:active:bg-red-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'blue' => [
                'bg' => 'bg-blue-50 dark:bg-blue-950/50',
                'text' => 'text-blue-700 dark:text-blue-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-blue-100 dark:hover:bg-blue-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-400 dark:focus-visible:ring-blue-500',
                'active' => 'active:bg-blue-200 dark:active:bg-blue-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'green' => [
                'bg' => 'bg-green-50 dark:bg-green-950/50',
                'text' => 'text-green-700 dark:text-green-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-green-100 dark:hover:bg-green-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-400 dark:focus-visible:ring-green-500',
                'active' => 'active:bg-green-200 dark:active:bg-green-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'yellow' => [
                'bg' => 'bg-yellow-50 dark:bg-yellow-950/50',
                'text' => 'text-yellow-700 dark:text-yellow-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-yellow-100 dark:hover:bg-yellow-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-yellow-400 dark:focus-visible:ring-yellow-500',
                'active' => 'active:bg-yellow-200 dark:active:bg-yellow-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'purple' => [
                'bg' => 'bg-purple-50 dark:bg-purple-950/50',
                'text' => 'text-purple-700 dark:text-purple-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-purple-100 dark:hover:bg-purple-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-400 dark:focus-visible:ring-purple-500',
                'active' => 'active:bg-purple-200 dark:active:bg-purple-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'pink' => [
                'bg' => 'bg-pink-50 dark:bg-pink-950/50',
                'text' => 'text-pink-700 dark:text-pink-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-pink-100 dark:hover:bg-pink-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pink-400 dark:focus-visible:ring-pink-500',
                'active' => 'active:bg-pink-200 dark:active:bg-pink-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'gray' => [
                'bg' => 'bg-gray-50 dark:bg-gray-950/50',
                'text' => 'text-gray-700 dark:text-gray-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-gray-100 dark:hover:bg-gray-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-400 dark:focus-visible:ring-gray-500',
                'active' => 'active:bg-gray-200 dark:active:bg-gray-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'orange' => [
                'bg' => 'bg-orange-50 dark:bg-orange-950/50',
                'text' => 'text-orange-700 dark:text-orange-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-orange-100 dark:hover:bg-orange-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-400 dark:focus-visible:ring-orange-500',
                'active' => 'active:bg-orange-200 dark:active:bg-orange-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'amber' => [
                'bg' => 'bg-amber-50 dark:bg-amber-950/50',
                'text' => 'text-amber-700 dark:text-amber-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-amber-100 dark:hover:bg-amber-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400 dark:focus-visible:ring-amber-500',
                'active' => 'active:bg-amber-200 dark:active:bg-amber-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'lime' => [
                'bg' => 'bg-lime-50 dark:bg-lime-950/50',
                'text' => 'text-lime-700 dark:text-lime-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-lime-100 dark:hover:bg-lime-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lime-400 dark:focus-visible:ring-lime-500',
                'active' => 'active:bg-lime-200 dark:active:bg-lime-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'emerald' => [
                'bg' => 'bg-emerald-50 dark:bg-emerald-950/50',
                'text' => 'text-emerald-700 dark:text-emerald-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-emerald-100 dark:hover:bg-emerald-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400 dark:focus-visible:ring-emerald-500',
                'active' => 'active:bg-emerald-200 dark:active:bg-emerald-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'teal' => [
                'bg' => 'bg-teal-50 dark:bg-teal-950/50',
                'text' => 'text-teal-700 dark:text-teal-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-teal-100 dark:hover:bg-teal-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-400 dark:focus-visible:ring-teal-500',
                'active' => 'active:bg-teal-200 dark:active:bg-teal-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'cyan' => [
                'bg' => 'bg-cyan-50 dark:bg-cyan-950/50',
                'text' => 'text-cyan-700 dark:text-cyan-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-cyan-100 dark:hover:bg-cyan-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400 dark:focus-visible:ring-cyan-500',
                'active' => 'active:bg-cyan-200 dark:active:bg-cyan-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'sky' => [
                'bg' => 'bg-sky-50 dark:bg-sky-950/50',
                'text' => 'text-sky-700 dark:text-sky-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-sky-100 dark:hover:bg-sky-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-400 dark:focus-visible:ring-sky-500',
                'active' => 'active:bg-sky-200 dark:active:bg-sky-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'indigo' => [
                'bg' => 'bg-indigo-50 dark:bg-indigo-950/50',
                'text' => 'text-indigo-700 dark:text-indigo-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-indigo-100 dark:hover:bg-indigo-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 dark:focus-visible:ring-indigo-500',
                'active' => 'active:bg-indigo-200 dark:active:bg-indigo-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'violet' => [
                'bg' => 'bg-violet-50 dark:bg-violet-950/50',
                'text' => 'text-violet-700 dark:text-violet-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-violet-100 dark:hover:bg-violet-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400 dark:focus-visible:ring-violet-500',
                'active' => 'active:bg-violet-200 dark:active:bg-violet-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'rose' => [
                'bg' => 'bg-rose-50 dark:bg-rose-950/50',
                'text' => 'text-rose-700 dark:text-rose-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-rose-100 dark:hover:bg-rose-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-400 dark:focus-visible:ring-rose-500',
                'active' => 'active:bg-rose-200 dark:active:bg-rose-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'fuchsia' => [
                'bg' => 'bg-fuchsia-50 dark:bg-fuchsia-950/50',
                'text' => 'text-fuchsia-700 dark:text-fuchsia-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-fuchsia-100 dark:hover:bg-fuchsia-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-fuchsia-400 dark:focus-visible:ring-fuchsia-500',
                'active' => 'active:bg-fuchsia-200 dark:active:bg-fuchsia-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'slate' => [
                'bg' => 'bg-slate-50 dark:bg-slate-950/50',
                'text' => 'text-slate-700 dark:text-slate-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-slate-100 dark:hover:bg-slate-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 dark:focus-visible:ring-slate-500',
                'active' => 'active:bg-slate-200 dark:active:bg-slate-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'stone' => [
                'bg' => 'bg-stone-50 dark:bg-stone-950/50',
                'text' => 'text-stone-700 dark:text-stone-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-stone-100 dark:hover:bg-stone-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-stone-400 dark:focus-visible:ring-stone-500',
                'active' => 'active:bg-stone-200 dark:active:bg-stone-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'zinc' => [
                'bg' => 'bg-zinc-50 dark:bg-zinc-950/50',
                'text' => 'text-zinc-700 dark:text-zinc-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-zinc-100 dark:hover:bg-zinc-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400 dark:focus-visible:ring-zinc-500',
                'active' => 'active:bg-zinc-200 dark:active:bg-zinc-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'neutral' => [
                'bg' => 'bg-neutral-50 dark:bg-neutral-950/50',
                'text' => 'text-neutral-700 dark:text-neutral-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-neutral-100 dark:hover:bg-neutral-900/50',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-400 dark:focus-visible:ring-neutral-500',
                'active' => 'active:bg-neutral-200 dark:active:bg-neutral-800/50',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
        ],

        'outline' => [
            'beartropy' => [
                'bg' => 'bg-transparent',
                'text' => 'text-beartropy-600 dark:text-beartropy-400',
                'border' => 'border-beartropy-200 dark:border-beartropy-800',
                'hover' => 'hover:bg-beartropy-50 hover:border-beartropy-300 dark:hover:bg-beartropy-950/30 dark:hover:border-beartropy-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-beartropy-400 dark:focus-visible:ring-beartropy-500',
                'active' => 'active:bg-beartropy-100 dark:active:bg-beartropy-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'red' => [
                'bg' => 'bg-transparent',
                'text' => 'text-red-600 dark:text-red-400',
                'border' => 'border-red-200 dark:border-red-800',
                'hover' => 'hover:bg-red-50 hover:border-red-300 dark:hover:bg-red-950/30 dark:hover:border-red-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-400 dark:focus-visible:ring-red-500',
                'active' => 'active:bg-red-100 dark:active:bg-red-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'blue' => [
                'bg' => 'bg-transparent',
                'text' => 'text-blue-600 dark:text-blue-400',
                'border' => 'border-blue-200 dark:border-blue-800',
                'hover' => 'hover:bg-blue-50 hover:border-blue-300 dark:hover:bg-blue-950/30 dark:hover:border-blue-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-400 dark:focus-visible:ring-blue-500',
                'active' => 'active:bg-blue-100 dark:active:bg-blue-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'green' => [
                'bg' => 'bg-transparent',
                'text' => 'text-green-600 dark:text-green-400',
                'border' => 'border-green-200 dark:border-green-800',
                'hover' => 'hover:bg-green-50 hover:border-green-300 dark:hover:bg-green-950/30 dark:hover:border-green-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-400 dark:focus-visible:ring-green-500',
                'active' => 'active:bg-green-100 dark:active:bg-green-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'yellow' => [
                'bg' => 'bg-transparent',
                'text' => 'text-yellow-600 dark:text-yellow-400',
                'border' => 'border-yellow-200 dark:border-yellow-800',
                'hover' => 'hover:bg-yellow-50 hover:border-yellow-300 dark:hover:bg-yellow-950/30 dark:hover:border-yellow-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-yellow-400 dark:focus-visible:ring-yellow-500',
                'active' => 'active:bg-yellow-100 dark:active:bg-yellow-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'purple' => [
                'bg' => 'bg-transparent',
                'text' => 'text-purple-600 dark:text-purple-400',
                'border' => 'border-purple-200 dark:border-purple-800',
                'hover' => 'hover:bg-purple-50 hover:border-purple-300 dark:hover:bg-purple-950/30 dark:hover:border-purple-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-400 dark:focus-visible:ring-purple-500',
                'active' => 'active:bg-purple-100 dark:active:bg-purple-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'pink' => [
                'bg' => 'bg-transparent',
                'text' => 'text-pink-600 dark:text-pink-400',
                'border' => 'border-pink-200 dark:border-pink-800',
                'hover' => 'hover:bg-pink-50 hover:border-pink-300 dark:hover:bg-pink-950/30 dark:hover:border-pink-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pink-400 dark:focus-visible:ring-pink-500',
                'active' => 'active:bg-pink-100 dark:active:bg-pink-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'gray' => [
                'bg' => 'bg-transparent',
                'text' => 'text-gray-600 dark:text-gray-400',
                'border' => 'border-gray-200 dark:border-gray-800',
                'hover' => 'hover:bg-gray-50 hover:border-gray-300 dark:hover:bg-gray-950/30 dark:hover:border-gray-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-400 dark:focus-visible:ring-gray-500',
                'active' => 'active:bg-gray-100 dark:active:bg-gray-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'orange' => [
                'bg' => 'bg-transparent',
                'text' => 'text-orange-600 dark:text-orange-400',
                'border' => 'border-orange-200 dark:border-orange-800',
                'hover' => 'hover:bg-orange-50 hover:border-orange-300 dark:hover:bg-orange-950/30 dark:hover:border-orange-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-400 dark:focus-visible:ring-orange-500',
                'active' => 'active:bg-orange-100 dark:active:bg-orange-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'amber' => [
                'bg' => 'bg-transparent',
                'text' => 'text-amber-600 dark:text-amber-400',
                'border' => 'border-amber-200 dark:border-amber-800',
                'hover' => 'hover:bg-amber-50 hover:border-amber-300 dark:hover:bg-amber-950/30 dark:hover:border-amber-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400 dark:focus-visible:ring-amber-500',
                'active' => 'active:bg-amber-100 dark:active:bg-amber-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'lime' => [
                'bg' => 'bg-transparent',
                'text' => 'text-lime-600 dark:text-lime-400',
                'border' => 'border-lime-200 dark:border-lime-800',
                'hover' => 'hover:bg-lime-50 hover:border-lime-300 dark:hover:bg-lime-950/30 dark:hover:border-lime-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lime-400 dark:focus-visible:ring-lime-500',
                'active' => 'active:bg-lime-100 dark:active:bg-lime-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'emerald' => [
                'bg' => 'bg-transparent',
                'text' => 'text-emerald-600 dark:text-emerald-400',
                'border' => 'border-emerald-200 dark:border-emerald-800',
                'hover' => 'hover:bg-emerald-50 hover:border-emerald-300 dark:hover:bg-emerald-950/30 dark:hover:border-emerald-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400 dark:focus-visible:ring-emerald-500',
                'active' => 'active:bg-emerald-100 dark:active:bg-emerald-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'teal' => [
                'bg' => 'bg-transparent',
                'text' => 'text-teal-600 dark:text-teal-400',
                'border' => 'border-teal-200 dark:border-teal-800',
                'hover' => 'hover:bg-teal-50 hover:border-teal-300 dark:hover:bg-teal-950/30 dark:hover:border-teal-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-400 dark:focus-visible:ring-teal-500',
                'active' => 'active:bg-teal-100 dark:active:bg-teal-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'cyan' => [
                'bg' => 'bg-transparent',
                'text' => 'text-cyan-600 dark:text-cyan-400',
                'border' => 'border-cyan-200 dark:border-cyan-800',
                'hover' => 'hover:bg-cyan-50 hover:border-cyan-300 dark:hover:bg-cyan-950/30 dark:hover:border-cyan-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400 dark:focus-visible:ring-cyan-500',
                'active' => 'active:bg-cyan-100 dark:active:bg-cyan-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'sky' => [
                'bg' => 'bg-transparent',
                'text' => 'text-sky-600 dark:text-sky-400',
                'border' => 'border-sky-200 dark:border-sky-800',
                'hover' => 'hover:bg-sky-50 hover:border-sky-300 dark:hover:bg-sky-950/30 dark:hover:border-sky-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-400 dark:focus-visible:ring-sky-500',
                'active' => 'active:bg-sky-100 dark:active:bg-sky-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'indigo' => [
                'bg' => 'bg-transparent',
                'text' => 'text-indigo-600 dark:text-indigo-400',
                'border' => 'border-indigo-200 dark:border-indigo-800',
                'hover' => 'hover:bg-indigo-50 hover:border-indigo-300 dark:hover:bg-indigo-950/30 dark:hover:border-indigo-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 dark:focus-visible:ring-indigo-500',
                'active' => 'active:bg-indigo-100 dark:active:bg-indigo-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'violet' => [
                'bg' => 'bg-transparent',
                'text' => 'text-violet-600 dark:text-violet-400',
                'border' => 'border-violet-200 dark:border-violet-800',
                'hover' => 'hover:bg-violet-50 hover:border-violet-300 dark:hover:bg-violet-950/30 dark:hover:border-violet-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400 dark:focus-visible:ring-violet-500',
                'active' => 'active:bg-violet-100 dark:active:bg-violet-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'rose' => [
                'bg' => 'bg-transparent',
                'text' => 'text-rose-600 dark:text-rose-400',
                'border' => 'border-rose-200 dark:border-rose-800',
                'hover' => 'hover:bg-rose-50 hover:border-rose-300 dark:hover:bg-rose-950/30 dark:hover:border-rose-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-400 dark:focus-visible:ring-rose-500',
                'active' => 'active:bg-rose-100 dark:active:bg-rose-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'fuchsia' => [
                'bg' => 'bg-transparent',
                'text' => 'text-fuchsia-600 dark:text-fuchsia-400',
                'border' => 'border-fuchsia-200 dark:border-fuchsia-800',
                'hover' => 'hover:bg-fuchsia-50 hover:border-fuchsia-300 dark:hover:bg-fuchsia-950/30 dark:hover:border-fuchsia-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-fuchsia-400 dark:focus-visible:ring-fuchsia-500',
                'active' => 'active:bg-fuchsia-100 dark:active:bg-fuchsia-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'slate' => [
                'bg' => 'bg-transparent',
                'text' => 'text-slate-600 dark:text-slate-400',
                'border' => 'border-slate-200 dark:border-slate-800',
                'hover' => 'hover:bg-slate-50 hover:border-slate-300 dark:hover:bg-slate-950/30 dark:hover:border-slate-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 dark:focus-visible:ring-slate-500',
                'active' => 'active:bg-slate-100 dark:active:bg-slate-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'stone' => [
                'bg' => 'bg-transparent',
                'text' => 'text-stone-600 dark:text-stone-400',
                'border' => 'border-stone-200 dark:border-stone-800',
                'hover' => 'hover:bg-stone-50 hover:border-stone-300 dark:hover:bg-stone-950/30 dark:hover:border-stone-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-stone-400 dark:focus-visible:ring-stone-500',
                'active' => 'active:bg-stone-100 dark:active:bg-stone-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'zinc' => [
                'bg' => 'bg-transparent',
                'text' => 'text-zinc-600 dark:text-zinc-400',
                'border' => 'border-zinc-200 dark:border-zinc-800',
                'hover' => 'hover:bg-zinc-50 hover:border-zinc-300 dark:hover:bg-zinc-950/30 dark:hover:border-zinc-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400 dark:focus-visible:ring-zinc-500',
                'active' => 'active:bg-zinc-100 dark:active:bg-zinc-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'neutral' => [
                'bg' => 'bg-transparent',
                'text' => 'text-neutral-600 dark:text-neutral-400',
                'border' => 'border-neutral-200 dark:border-neutral-800',
                'hover' => 'hover:bg-neutral-50 hover:border-neutral-300 dark:hover:bg-neutral-950/30 dark:hover:border-neutral-700',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-400 dark:focus-visible:ring-neutral-500',
                'active' => 'active:bg-neutral-100 dark:active:bg-neutral-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
        ],

        'ghost' => [
            'beartropy' => [
                'bg' => 'bg-transparent',
                'text' => 'text-beartropy-600 dark:text-beartropy-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-beartropy-50 dark:hover:bg-beartropy-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-beartropy-400 dark:focus-visible:ring-beartropy-500',
                'active' => 'active:bg-beartropy-100 dark:active:bg-beartropy-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'red' => [
                'bg' => 'bg-transparent',
                'text' => 'text-red-600 dark:text-red-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-red-50 dark:hover:bg-red-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-400 dark:focus-visible:ring-red-500',
                'active' => 'active:bg-red-100 dark:active:bg-red-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'blue' => [
                'bg' => 'bg-transparent',
                'text' => 'text-blue-600 dark:text-blue-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-blue-50 dark:hover:bg-blue-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-400 dark:focus-visible:ring-blue-500',
                'active' => 'active:bg-blue-100 dark:active:bg-blue-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'green' => [
                'bg' => 'bg-transparent',
                'text' => 'text-green-600 dark:text-green-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-green-50 dark:hover:bg-green-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-400 dark:focus-visible:ring-green-500',
                'active' => 'active:bg-green-100 dark:active:bg-green-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'yellow' => [
                'bg' => 'bg-transparent',
                'text' => 'text-yellow-600 dark:text-yellow-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-yellow-50 dark:hover:bg-yellow-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-yellow-400 dark:focus-visible:ring-yellow-500',
                'active' => 'active:bg-yellow-100 dark:active:bg-yellow-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'purple' => [
                'bg' => 'bg-transparent',
                'text' => 'text-purple-600 dark:text-purple-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-purple-50 dark:hover:bg-purple-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-400 dark:focus-visible:ring-purple-500',
                'active' => 'active:bg-purple-100 dark:active:bg-purple-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'pink' => [
                'bg' => 'bg-transparent',
                'text' => 'text-pink-600 dark:text-pink-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-pink-50 dark:hover:bg-pink-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pink-400 dark:focus-visible:ring-pink-500',
                'active' => 'active:bg-pink-100 dark:active:bg-pink-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'gray' => [
                'bg' => 'bg-transparent',
                'text' => 'text-gray-600 dark:text-gray-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-gray-50 dark:hover:bg-gray-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-400 dark:focus-visible:ring-gray-500',
                'active' => 'active:bg-gray-100 dark:active:bg-gray-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'orange' => [
                'bg' => 'bg-transparent',
                'text' => 'text-orange-600 dark:text-orange-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-orange-50 dark:hover:bg-orange-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-400 dark:focus-visible:ring-orange-500',
                'active' => 'active:bg-orange-100 dark:active:bg-orange-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'amber' => [
                'bg' => 'bg-transparent',
                'text' => 'text-amber-600 dark:text-amber-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-amber-50 dark:hover:bg-amber-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400 dark:focus-visible:ring-amber-500',
                'active' => 'active:bg-amber-100 dark:active:bg-amber-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'lime' => [
                'bg' => 'bg-transparent',
                'text' => 'text-lime-600 dark:text-lime-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-lime-50 dark:hover:bg-lime-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lime-400 dark:focus-visible:ring-lime-500',
                'active' => 'active:bg-lime-100 dark:active:bg-lime-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'emerald' => [
                'bg' => 'bg-transparent',
                'text' => 'text-emerald-600 dark:text-emerald-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-emerald-50 dark:hover:bg-emerald-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400 dark:focus-visible:ring-emerald-500',
                'active' => 'active:bg-emerald-100 dark:active:bg-emerald-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'teal' => [
                'bg' => 'bg-transparent',
                'text' => 'text-teal-600 dark:text-teal-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-teal-50 dark:hover:bg-teal-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-400 dark:focus-visible:ring-teal-500',
                'active' => 'active:bg-teal-100 dark:active:bg-teal-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'cyan' => [
                'bg' => 'bg-transparent',
                'text' => 'text-cyan-600 dark:text-cyan-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-cyan-50 dark:hover:bg-cyan-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400 dark:focus-visible:ring-cyan-500',
                'active' => 'active:bg-cyan-100 dark:active:bg-cyan-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'sky' => [
                'bg' => 'bg-transparent',
                'text' => 'text-sky-600 dark:text-sky-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-sky-50 dark:hover:bg-sky-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-400 dark:focus-visible:ring-sky-500',
                'active' => 'active:bg-sky-100 dark:active:bg-sky-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'indigo' => [
                'bg' => 'bg-transparent',
                'text' => 'text-indigo-600 dark:text-indigo-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-indigo-50 dark:hover:bg-indigo-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 dark:focus-visible:ring-indigo-500',
                'active' => 'active:bg-indigo-100 dark:active:bg-indigo-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'violet' => [
                'bg' => 'bg-transparent',
                'text' => 'text-violet-600 dark:text-violet-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-violet-50 dark:hover:bg-violet-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400 dark:focus-visible:ring-violet-500',
                'active' => 'active:bg-violet-100 dark:active:bg-violet-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'rose' => [
                'bg' => 'bg-transparent',
                'text' => 'text-rose-600 dark:text-rose-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-rose-50 dark:hover:bg-rose-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-400 dark:focus-visible:ring-rose-500',
                'active' => 'active:bg-rose-100 dark:active:bg-rose-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'fuchsia' => [
                'bg' => 'bg-transparent',
                'text' => 'text-fuchsia-600 dark:text-fuchsia-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-fuchsia-50 dark:hover:bg-fuchsia-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-fuchsia-400 dark:focus-visible:ring-fuchsia-500',
                'active' => 'active:bg-fuchsia-100 dark:active:bg-fuchsia-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'slate' => [
                'bg' => 'bg-transparent',
                'text' => 'text-slate-600 dark:text-slate-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-slate-50 dark:hover:bg-slate-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 dark:focus-visible:ring-slate-500',
                'active' => 'active:bg-slate-100 dark:active:bg-slate-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'stone' => [
                'bg' => 'bg-transparent',
                'text' => 'text-stone-600 dark:text-stone-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-stone-50 dark:hover:bg-stone-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-stone-400 dark:focus-visible:ring-stone-500',
                'active' => 'active:bg-stone-100 dark:active:bg-stone-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'zinc' => [
                'bg' => 'bg-transparent',
                'text' => 'text-zinc-600 dark:text-zinc-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-zinc-50 dark:hover:bg-zinc-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400 dark:focus-visible:ring-zinc-500',
                'active' => 'active:bg-zinc-100 dark:active:bg-zinc-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'neutral' => [
                'bg' => 'bg-transparent',
                'text' => 'text-neutral-600 dark:text-neutral-400',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-neutral-50 dark:hover:bg-neutral-950/30',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-400 dark:focus-visible:ring-neutral-500',
                'active' => 'active:bg-neutral-100 dark:active:bg-neutral-900/40',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
        ],

        'tint' => [
            'beartropy' => [
                'bg' => 'bg-beartropy-500/10 dark:bg-beartropy-400/10',
                'text' => 'text-beartropy-700 dark:text-beartropy-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-beartropy-500/15 dark:hover:bg-beartropy-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-beartropy-400 dark:focus-visible:ring-beartropy-500',
                'active' => 'active:bg-beartropy-500/20 dark:active:bg-beartropy-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'red' => [
                'bg' => 'bg-red-500/10 dark:bg-red-400/10',
                'text' => 'text-red-700 dark:text-red-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-red-500/15 dark:hover:bg-red-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-400 dark:focus-visible:ring-red-500',
                'active' => 'active:bg-red-500/20 dark:active:bg-red-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'blue' => [
                'bg' => 'bg-blue-500/10 dark:bg-blue-400/10',
                'text' => 'text-blue-700 dark:text-blue-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-blue-500/15 dark:hover:bg-blue-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-400 dark:focus-visible:ring-blue-500',
                'active' => 'active:bg-blue-500/20 dark:active:bg-blue-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'green' => [
                'bg' => 'bg-green-500/10 dark:bg-green-400/10',
                'text' => 'text-green-700 dark:text-green-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-green-500/15 dark:hover:bg-green-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-400 dark:focus-visible:ring-green-500',
                'active' => 'active:bg-green-500/20 dark:active:bg-green-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'yellow' => [
                'bg' => 'bg-yellow-500/10 dark:bg-yellow-400/10',
                'text' => 'text-yellow-700 dark:text-yellow-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-yellow-500/15 dark:hover:bg-yellow-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-yellow-400 dark:focus-visible:ring-yellow-500',
                'active' => 'active:bg-yellow-500/20 dark:active:bg-yellow-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'purple' => [
                'bg' => 'bg-purple-500/10 dark:bg-purple-400/10',
                'text' => 'text-purple-700 dark:text-purple-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-purple-500/15 dark:hover:bg-purple-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-400 dark:focus-visible:ring-purple-500',
                'active' => 'active:bg-purple-500/20 dark:active:bg-purple-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'pink' => [
                'bg' => 'bg-pink-500/10 dark:bg-pink-400/10',
                'text' => 'text-pink-700 dark:text-pink-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-pink-500/15 dark:hover:bg-pink-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pink-400 dark:focus-visible:ring-pink-500',
                'active' => 'active:bg-pink-500/20 dark:active:bg-pink-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'gray' => [
                'bg' => 'bg-gray-500/10 dark:bg-gray-400/10',
                'text' => 'text-gray-700 dark:text-gray-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-gray-500/15 dark:hover:bg-gray-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-400 dark:focus-visible:ring-gray-500',
                'active' => 'active:bg-gray-500/20 dark:active:bg-gray-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'orange' => [
                'bg' => 'bg-orange-500/10 dark:bg-orange-400/10',
                'text' => 'text-orange-700 dark:text-orange-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-orange-500/15 dark:hover:bg-orange-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-400 dark:focus-visible:ring-orange-500',
                'active' => 'active:bg-orange-500/20 dark:active:bg-orange-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'amber' => [
                'bg' => 'bg-amber-500/10 dark:bg-amber-400/10',
                'text' => 'text-amber-700 dark:text-amber-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-amber-500/15 dark:hover:bg-amber-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400 dark:focus-visible:ring-amber-500',
                'active' => 'active:bg-amber-500/20 dark:active:bg-amber-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'lime' => [
                'bg' => 'bg-lime-500/10 dark:bg-lime-400/10',
                'text' => 'text-lime-700 dark:text-lime-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-lime-500/15 dark:hover:bg-lime-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lime-400 dark:focus-visible:ring-lime-500',
                'active' => 'active:bg-lime-500/20 dark:active:bg-lime-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'emerald' => [
                'bg' => 'bg-emerald-500/10 dark:bg-emerald-400/10',
                'text' => 'text-emerald-700 dark:text-emerald-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-emerald-500/15 dark:hover:bg-emerald-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400 dark:focus-visible:ring-emerald-500',
                'active' => 'active:bg-emerald-500/20 dark:active:bg-emerald-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'teal' => [
                'bg' => 'bg-teal-500/10 dark:bg-teal-400/10',
                'text' => 'text-teal-700 dark:text-teal-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-teal-500/15 dark:hover:bg-teal-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-400 dark:focus-visible:ring-teal-500',
                'active' => 'active:bg-teal-500/20 dark:active:bg-teal-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'cyan' => [
                'bg' => 'bg-cyan-500/10 dark:bg-cyan-400/10',
                'text' => 'text-cyan-700 dark:text-cyan-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-cyan-500/15 dark:hover:bg-cyan-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400 dark:focus-visible:ring-cyan-500',
                'active' => 'active:bg-cyan-500/20 dark:active:bg-cyan-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'sky' => [
                'bg' => 'bg-sky-500/10 dark:bg-sky-400/10',
                'text' => 'text-sky-700 dark:text-sky-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-sky-500/15 dark:hover:bg-sky-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-400 dark:focus-visible:ring-sky-500',
                'active' => 'active:bg-sky-500/20 dark:active:bg-sky-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'indigo' => [
                'bg' => 'bg-indigo-500/10 dark:bg-indigo-400/10',
                'text' => 'text-indigo-700 dark:text-indigo-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-indigo-500/15 dark:hover:bg-indigo-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 dark:focus-visible:ring-indigo-500',
                'active' => 'active:bg-indigo-500/20 dark:active:bg-indigo-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'violet' => [
                'bg' => 'bg-violet-500/10 dark:bg-violet-400/10',
                'text' => 'text-violet-700 dark:text-violet-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-violet-500/15 dark:hover:bg-violet-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400 dark:focus-visible:ring-violet-500',
                'active' => 'active:bg-violet-500/20 dark:active:bg-violet-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'rose' => [
                'bg' => 'bg-rose-500/10 dark:bg-rose-400/10',
                'text' => 'text-rose-700 dark:text-rose-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-rose-500/15 dark:hover:bg-rose-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-400 dark:focus-visible:ring-rose-500',
                'active' => 'active:bg-rose-500/20 dark:active:bg-rose-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'fuchsia' => [
                'bg' => 'bg-fuchsia-500/10 dark:bg-fuchsia-400/10',
                'text' => 'text-fuchsia-700 dark:text-fuchsia-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-fuchsia-500/15 dark:hover:bg-fuchsia-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-fuchsia-400 dark:focus-visible:ring-fuchsia-500',
                'active' => 'active:bg-fuchsia-500/20 dark:active:bg-fuchsia-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'slate' => [
                'bg' => 'bg-slate-500/10 dark:bg-slate-400/10',
                'text' => 'text-slate-700 dark:text-slate-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-slate-500/15 dark:hover:bg-slate-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 dark:focus-visible:ring-slate-500',
                'active' => 'active:bg-slate-500/20 dark:active:bg-slate-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'stone' => [
                'bg' => 'bg-stone-500/10 dark:bg-stone-400/10',
                'text' => 'text-stone-700 dark:text-stone-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-stone-500/15 dark:hover:bg-stone-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-stone-400 dark:focus-visible:ring-stone-500',
                'active' => 'active:bg-stone-500/20 dark:active:bg-stone-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'zinc' => [
                'bg' => 'bg-zinc-500/10 dark:bg-zinc-400/10',
                'text' => 'text-zinc-700 dark:text-zinc-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-zinc-500/15 dark:hover:bg-zinc-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400 dark:focus-visible:ring-zinc-500',
                'active' => 'active:bg-zinc-500/20 dark:active:bg-zinc-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'neutral' => [
                'bg' => 'bg-neutral-500/10 dark:bg-neutral-400/10',
                'text' => 'text-neutral-700 dark:text-neutral-300',
                'border' => 'border-transparent',
                'hover' => 'hover:bg-neutral-500/15 dark:hover:bg-neutral-400/15',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-400 dark:focus-visible:ring-neutral-500',
                'active' => 'active:bg-neutral-500/20 dark:active:bg-neutral-400/20',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
        ],

        'glass' => [
            'beartropy' => [
                'bg' => 'bg-beartropy-400/15 backdrop-blur-lg dark:bg-beartropy-500/15',
                'text' => 'text-beartropy-800 dark:text-beartropy-200',
                'border' => 'border-beartropy-300/20 dark:border-beartropy-500/20',
                'hover' => 'hover:bg-beartropy-400/25 dark:hover:bg-beartropy-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-beartropy-400/60 dark:focus-visible:ring-beartropy-500/40',
                'active' => 'active:bg-beartropy-400/30 dark:active:bg-beartropy-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'red' => [
                'bg' => 'bg-red-400/15 backdrop-blur-lg dark:bg-red-500/15',
                'text' => 'text-red-800 dark:text-red-200',
                'border' => 'border-red-300/20 dark:border-red-500/20',
                'hover' => 'hover:bg-red-400/25 dark:hover:bg-red-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-400/60 dark:focus-visible:ring-red-500/40',
                'active' => 'active:bg-red-400/30 dark:active:bg-red-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'blue' => [
                'bg' => 'bg-blue-400/15 backdrop-blur-lg dark:bg-blue-500/15',
                'text' => 'text-blue-800 dark:text-blue-200',
                'border' => 'border-blue-300/20 dark:border-blue-500/20',
                'hover' => 'hover:bg-blue-400/25 dark:hover:bg-blue-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-400/60 dark:focus-visible:ring-blue-500/40',
                'active' => 'active:bg-blue-400/30 dark:active:bg-blue-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'green' => [
                'bg' => 'bg-green-400/15 backdrop-blur-lg dark:bg-green-500/15',
                'text' => 'text-green-800 dark:text-green-200',
                'border' => 'border-green-300/20 dark:border-green-500/20',
                'hover' => 'hover:bg-green-400/25 dark:hover:bg-green-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-400/60 dark:focus-visible:ring-green-500/40',
                'active' => 'active:bg-green-400/30 dark:active:bg-green-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'yellow' => [
                'bg' => 'bg-yellow-400/15 backdrop-blur-lg dark:bg-yellow-500/15',
                'text' => 'text-yellow-800 dark:text-yellow-200',
                'border' => 'border-yellow-300/20 dark:border-yellow-500/20',
                'hover' => 'hover:bg-yellow-400/25 dark:hover:bg-yellow-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-yellow-400/60 dark:focus-visible:ring-yellow-500/40',
                'active' => 'active:bg-yellow-400/30 dark:active:bg-yellow-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'purple' => [
                'bg' => 'bg-purple-400/15 backdrop-blur-lg dark:bg-purple-500/15',
                'text' => 'text-purple-800 dark:text-purple-200',
                'border' => 'border-purple-300/20 dark:border-purple-500/20',
                'hover' => 'hover:bg-purple-400/25 dark:hover:bg-purple-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-400/60 dark:focus-visible:ring-purple-500/40',
                'active' => 'active:bg-purple-400/30 dark:active:bg-purple-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'pink' => [
                'bg' => 'bg-pink-400/15 backdrop-blur-lg dark:bg-pink-500/15',
                'text' => 'text-pink-800 dark:text-pink-200',
                'border' => 'border-pink-300/20 dark:border-pink-500/20',
                'hover' => 'hover:bg-pink-400/25 dark:hover:bg-pink-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pink-400/60 dark:focus-visible:ring-pink-500/40',
                'active' => 'active:bg-pink-400/30 dark:active:bg-pink-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'gray' => [
                'bg' => 'bg-gray-400/15 backdrop-blur-lg dark:bg-gray-500/15',
                'text' => 'text-gray-800 dark:text-gray-200',
                'border' => 'border-gray-300/20 dark:border-gray-500/20',
                'hover' => 'hover:bg-gray-400/25 dark:hover:bg-gray-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-400/60 dark:focus-visible:ring-gray-500/40',
                'active' => 'active:bg-gray-400/30 dark:active:bg-gray-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'orange' => [
                'bg' => 'bg-orange-400/15 backdrop-blur-lg dark:bg-orange-500/15',
                'text' => 'text-orange-800 dark:text-orange-200',
                'border' => 'border-orange-300/20 dark:border-orange-500/20',
                'hover' => 'hover:bg-orange-400/25 dark:hover:bg-orange-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-400/60 dark:focus-visible:ring-orange-500/40',
                'active' => 'active:bg-orange-400/30 dark:active:bg-orange-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'amber' => [
                'bg' => 'bg-amber-400/15 backdrop-blur-lg dark:bg-amber-500/15',
                'text' => 'text-amber-800 dark:text-amber-200',
                'border' => 'border-amber-300/20 dark:border-amber-500/20',
                'hover' => 'hover:bg-amber-400/25 dark:hover:bg-amber-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400/60 dark:focus-visible:ring-amber-500/40',
                'active' => 'active:bg-amber-400/30 dark:active:bg-amber-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'lime' => [
                'bg' => 'bg-lime-400/15 backdrop-blur-lg dark:bg-lime-500/15',
                'text' => 'text-lime-800 dark:text-lime-200',
                'border' => 'border-lime-300/20 dark:border-lime-500/20',
                'hover' => 'hover:bg-lime-400/25 dark:hover:bg-lime-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lime-400/60 dark:focus-visible:ring-lime-500/40',
                'active' => 'active:bg-lime-400/30 dark:active:bg-lime-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'emerald' => [
                'bg' => 'bg-emerald-400/15 backdrop-blur-lg dark:bg-emerald-500/15',
                'text' => 'text-emerald-800 dark:text-emerald-200',
                'border' => 'border-emerald-300/20 dark:border-emerald-500/20',
                'hover' => 'hover:bg-emerald-400/25 dark:hover:bg-emerald-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400/60 dark:focus-visible:ring-emerald-500/40',
                'active' => 'active:bg-emerald-400/30 dark:active:bg-emerald-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'teal' => [
                'bg' => 'bg-teal-400/15 backdrop-blur-lg dark:bg-teal-500/15',
                'text' => 'text-teal-800 dark:text-teal-200',
                'border' => 'border-teal-300/20 dark:border-teal-500/20',
                'hover' => 'hover:bg-teal-400/25 dark:hover:bg-teal-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-400/60 dark:focus-visible:ring-teal-500/40',
                'active' => 'active:bg-teal-400/30 dark:active:bg-teal-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'cyan' => [
                'bg' => 'bg-cyan-400/15 backdrop-blur-lg dark:bg-cyan-500/15',
                'text' => 'text-cyan-800 dark:text-cyan-200',
                'border' => 'border-cyan-300/20 dark:border-cyan-500/20',
                'hover' => 'hover:bg-cyan-400/25 dark:hover:bg-cyan-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400/60 dark:focus-visible:ring-cyan-500/40',
                'active' => 'active:bg-cyan-400/30 dark:active:bg-cyan-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'sky' => [
                'bg' => 'bg-sky-400/15 backdrop-blur-lg dark:bg-sky-500/15',
                'text' => 'text-sky-800 dark:text-sky-200',
                'border' => 'border-sky-300/20 dark:border-sky-500/20',
                'hover' => 'hover:bg-sky-400/25 dark:hover:bg-sky-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-400/60 dark:focus-visible:ring-sky-500/40',
                'active' => 'active:bg-sky-400/30 dark:active:bg-sky-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'indigo' => [
                'bg' => 'bg-indigo-400/15 backdrop-blur-lg dark:bg-indigo-500/15',
                'text' => 'text-indigo-800 dark:text-indigo-200',
                'border' => 'border-indigo-300/20 dark:border-indigo-500/20',
                'hover' => 'hover:bg-indigo-400/25 dark:hover:bg-indigo-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400/60 dark:focus-visible:ring-indigo-500/40',
                'active' => 'active:bg-indigo-400/30 dark:active:bg-indigo-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'violet' => [
                'bg' => 'bg-violet-400/15 backdrop-blur-lg dark:bg-violet-500/15',
                'text' => 'text-violet-800 dark:text-violet-200',
                'border' => 'border-violet-300/20 dark:border-violet-500/20',
                'hover' => 'hover:bg-violet-400/25 dark:hover:bg-violet-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400/60 dark:focus-visible:ring-violet-500/40',
                'active' => 'active:bg-violet-400/30 dark:active:bg-violet-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'rose' => [
                'bg' => 'bg-rose-400/15 backdrop-blur-lg dark:bg-rose-500/15',
                'text' => 'text-rose-800 dark:text-rose-200',
                'border' => 'border-rose-300/20 dark:border-rose-500/20',
                'hover' => 'hover:bg-rose-400/25 dark:hover:bg-rose-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-400/60 dark:focus-visible:ring-rose-500/40',
                'active' => 'active:bg-rose-400/30 dark:active:bg-rose-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'fuchsia' => [
                'bg' => 'bg-fuchsia-400/15 backdrop-blur-lg dark:bg-fuchsia-500/15',
                'text' => 'text-fuchsia-800 dark:text-fuchsia-200',
                'border' => 'border-fuchsia-300/20 dark:border-fuchsia-500/20',
                'hover' => 'hover:bg-fuchsia-400/25 dark:hover:bg-fuchsia-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-fuchsia-400/60 dark:focus-visible:ring-fuchsia-500/40',
                'active' => 'active:bg-fuchsia-400/30 dark:active:bg-fuchsia-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'slate' => [
                'bg' => 'bg-slate-400/15 backdrop-blur-lg dark:bg-slate-500/15',
                'text' => 'text-slate-800 dark:text-slate-200',
                'border' => 'border-slate-300/20 dark:border-slate-500/20',
                'hover' => 'hover:bg-slate-400/25 dark:hover:bg-slate-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400/60 dark:focus-visible:ring-slate-500/40',
                'active' => 'active:bg-slate-400/30 dark:active:bg-slate-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'stone' => [
                'bg' => 'bg-stone-400/15 backdrop-blur-lg dark:bg-stone-500/15',
                'text' => 'text-stone-800 dark:text-stone-200',
                'border' => 'border-stone-300/20 dark:border-stone-500/20',
                'hover' => 'hover:bg-stone-400/25 dark:hover:bg-stone-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-stone-400/60 dark:focus-visible:ring-stone-500/40',
                'active' => 'active:bg-stone-400/30 dark:active:bg-stone-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'zinc' => [
                'bg' => 'bg-zinc-400/15 backdrop-blur-lg dark:bg-zinc-500/15',
                'text' => 'text-zinc-800 dark:text-zinc-200',
                'border' => 'border-zinc-300/20 dark:border-zinc-500/20',
                'hover' => 'hover:bg-zinc-400/25 dark:hover:bg-zinc-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400/60 dark:focus-visible:ring-zinc-500/40',
                'active' => 'active:bg-zinc-400/30 dark:active:bg-zinc-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'neutral' => [
                'bg' => 'bg-neutral-400/15 backdrop-blur-lg dark:bg-neutral-500/15',
                'text' => 'text-neutral-800 dark:text-neutral-200',
                'border' => 'border-neutral-300/20 dark:border-neutral-500/20',
                'hover' => 'hover:bg-neutral-400/25 dark:hover:bg-neutral-500/25',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-400/60 dark:focus-visible:ring-neutral-500/40',
                'active' => 'active:bg-neutral-400/30 dark:active:bg-neutral-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
        ],

        'gradient' => [
            'beartropy' => [
                'bg' => 'bg-gradient-to-r from-beartropy-500 to-cyan-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-beartropy-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'red' => [
                'bg' => 'bg-gradient-to-r from-red-500 to-rose-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'blue' => [
                'bg' => 'bg-gradient-to-r from-blue-500 to-cyan-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'green' => [
                'bg' => 'bg-gradient-to-r from-green-500 to-emerald-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-green-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'yellow' => [
                'bg' => 'bg-gradient-to-r from-yellow-400 to-amber-300 shadow-md',
                'text' => 'text-neutral-900',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-yellow-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'purple' => [
                'bg' => 'bg-gradient-to-r from-purple-500 to-fuchsia-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-purple-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'pink' => [
                'bg' => 'bg-gradient-to-r from-pink-500 to-rose-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-pink-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'gray' => [
                'bg' => 'bg-gradient-to-r from-gray-500 to-slate-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'orange' => [
                'bg' => 'bg-gradient-to-r from-orange-500 to-amber-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'amber' => [
                'bg' => 'bg-gradient-to-r from-amber-400 to-yellow-300 shadow-md',
                'text' => 'text-neutral-900',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'lime' => [
                'bg' => 'bg-gradient-to-r from-lime-400 to-green-300 shadow-md',
                'text' => 'text-neutral-900',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-lime-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'emerald' => [
                'bg' => 'bg-gradient-to-r from-emerald-500 to-teal-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'teal' => [
                'bg' => 'bg-gradient-to-r from-teal-500 to-cyan-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'cyan' => [
                'bg' => 'bg-gradient-to-r from-cyan-400 to-sky-300 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'sky' => [
                'bg' => 'bg-gradient-to-r from-sky-400 to-blue-300 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'indigo' => [
                'bg' => 'bg-gradient-to-r from-indigo-500 to-blue-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'violet' => [
                'bg' => 'bg-gradient-to-r from-violet-500 to-purple-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'rose' => [
                'bg' => 'bg-gradient-to-r from-rose-500 to-pink-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'fuchsia' => [
                'bg' => 'bg-gradient-to-r from-fuchsia-500 to-purple-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-fuchsia-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'slate' => [
                'bg' => 'bg-gradient-to-r from-slate-500 to-gray-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'stone' => [
                'bg' => 'bg-gradient-to-r from-stone-500 to-neutral-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-stone-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'zinc' => [
                'bg' => 'bg-gradient-to-r from-zinc-500 to-gray-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
            'neutral' => [
                'bg' => 'bg-gradient-to-r from-neutral-500 to-stone-400 shadow-md',
                'text' => 'text-white',
                'border' => 'border-none',
                'hover' => 'hover:brightness-110 hover:shadow-lg',
                'focus' => 'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-400 focus-visible:ring-offset-2 dark:ring-offset-black',
                'active' => 'active:brightness-95 active:shadow-sm',
                'disabled' => 'opacity-60 cursor-not-allowed pointer-events-none',
            ],
        ],

    ],
];
