<?php

return [
    'colors' => [
        'solid' => [
            'beartropy' => [
                'bg'       => 'bg-beartropy-600 dark:bg-beartropy-700',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-beartropy-700 dark:hover:bg-beartropy-500',
                'focus'    => 'focus:ring-2 focus:ring-beartropy-400 focus:ring-offset-2 dark:focus:ring-beartropy-300',
                'active'   => 'active:bg-beartropy-800 dark:active:bg-beartropy-600',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'red' => [
                'bg'       => 'bg-red-600 dark:bg-red-700',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-red-700 dark:hover:bg-red-600',
                'focus'    => 'focus:ring-2 focus:ring-red-400 focus:ring-offset-2 dark:focus:ring-red-300',
                'active'   => 'active:bg-red-800 dark:active:bg-red-700',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'blue' => [
                'bg'       => 'bg-blue-600 dark:bg-blue-700',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-blue-700 dark:hover:bg-blue-600',
                'focus'    => 'focus:ring-2 focus:ring-blue-400 focus:ring-offset-2 dark:focus:ring-blue-300',
                'active'   => 'active:bg-blue-800 dark:active:bg-blue-700',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'green' => [
                'bg'       => 'bg-green-600 dark:bg-green-700',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-green-700 dark:hover:bg-green-600',
                'focus'    => 'focus:ring-2 focus:ring-green-400 focus:ring-offset-2 dark:focus:ring-green-300',
                'active'   => 'active:bg-green-800 dark:active:bg-green-700',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'yellow' => [
                'bg'       => 'bg-yellow-400 dark:bg-yellow-300',
                'text'     => 'text-neutral-800',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-yellow-500 dark:hover:bg-yellow-400',
                'focus'    => 'focus:ring-2 focus:ring-yellow-300 focus:ring-offset-2 dark:focus:ring-yellow-200',
                'active'   => 'active:bg-yellow-500 dark:active:bg-yellow-500',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'purple' => [
                'bg'       => 'bg-purple-600 dark:bg-purple-600',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-purple-700 dark:hover:bg-purple-600',
                'focus'    => 'focus:ring-2 focus:ring-purple-400 focus:ring-offset-2 dark:focus:ring-purple-300',
                'active'   => 'active:bg-purple-800 dark:active:bg-purple-700',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'pink' => [
                'bg'       => 'bg-pink-600 dark:bg-pink-600',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-pink-700 dark:hover:bg-pink-600',
                'focus'    => 'focus:ring-2 focus:ring-pink-400 focus:ring-offset-2 dark:focus:ring-pink-300',
                'active'   => 'active:bg-pink-800 dark:active:bg-pink-700',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'gray' => [
                'bg'       => 'bg-gray-600 dark:bg-gray-500',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-gray-700 dark:hover:bg-gray-600',
                'focus'    => 'focus:ring-2 focus:ring-gray-400 focus:ring-offset-2 dark:focus:ring-gray-300',
                'active'   => 'active:bg-gray-800 dark:active:bg-gray-700',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'orange' => [
                'bg'       => 'bg-orange-500 dark:bg-orange-500',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-orange-600 dark:hover:bg-orange-500',
                'focus'    => 'focus:ring-2 focus:ring-orange-400 focus:ring-offset-2 dark:focus:ring-orange-300',
                'active'   => 'active:bg-orange-700 dark:active:bg-orange-600',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'amber' => [
                'bg'       => 'bg-amber-400 dark:bg-amber-500',
                'text'     => 'text-neutral-800',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-amber-500 dark:hover:bg-amber-400',
                'focus'    => 'focus:ring-2 focus:ring-amber-300 focus:ring-offset-2 dark:focus:ring-amber-200',
                'active'   => 'active:bg-amber-500 dark:active:bg-amber-500',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'lime' => [
                'bg'       => 'bg-lime-500 dark:bg-lime-600',
                'text'     => 'text-neutral-800',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-lime-600 dark:hover:bg-lime-500',
                'focus'    => 'focus:ring-2 focus:ring-lime-300 focus:ring-offset-2 dark:focus:ring-lime-200',
                'active'   => 'active:bg-lime-700 dark:active:bg-lime-600',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'emerald' => [
                'bg'       => 'bg-emerald-500 dark:bg-emerald-600',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-emerald-600 dark:hover:bg-emerald-500',
                'focus'    => 'focus:ring-2 focus:ring-emerald-300 focus:ring-offset-2 dark:focus:ring-emerald-200',
                'active'   => 'active:bg-emerald-700 dark:active:bg-emerald-600',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'teal' => [
                'bg'       => 'bg-teal-500 dark:bg-teal-600',
                'text'     => 'text-neutral-800',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-teal-600 dark:hover:bg-teal-500',
                'focus'    => 'focus:ring-2 focus:ring-teal-300 focus:ring-offset-2 dark:focus:ring-teal-200',
                'active'   => 'active:bg-teal-700 dark:active:bg-teal-600',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'cyan' => [
                'bg'       => 'bg-cyan-500 dark:bg-cyan-600',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-cyan-600 dark:hover:bg-cyan-500',
                'focus'    => 'focus:ring-2 focus:ring-cyan-300 focus:ring-offset-2 dark:focus:ring-cyan-200',
                'active'   => 'active:bg-cyan-700 dark:active:bg-cyan-600',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'sky' => [
                'bg'       => 'bg-sky-500 dark:bg-sky-600',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-sky-600 dark:hover:bg-sky-500',
                'focus'    => 'focus:ring-2 focus:ring-sky-300 focus:ring-offset-2 dark:focus:ring-sky-200',
                'active'   => 'active:bg-sky-700 dark:active:bg-sky-600',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'indigo' => [
                'bg'       => 'bg-indigo-600 dark:bg-indigo-500',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-indigo-700 dark:hover:bg-indigo-600',
                'focus'    => 'focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2 dark:focus:ring-indigo-300',
                'active'   => 'active:bg-indigo-800 dark:active:bg-indigo-700',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'violet' => [
                'bg'       => 'bg-violet-600 dark:bg-violet-600',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-violet-700 dark:hover:bg-violet-600',
                'focus'    => 'focus:ring-2 focus:ring-violet-400 focus:ring-offset-2 dark:focus:ring-violet-300',
                'active'   => 'active:bg-violet-800 dark:active:bg-violet-700',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'rose' => [
                'bg'       => 'bg-rose-600 dark:bg-rose-500',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-rose-700 dark:hover:bg-rose-600',
                'focus'    => 'focus:ring-2 focus:ring-rose-400 focus:ring-offset-2 dark:focus:ring-rose-300',
                'active'   => 'active:bg-rose-800 dark:active:bg-rose-700',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'fuchsia' => [
                'bg'       => 'bg-fuchsia-600 dark:bg-fuchsia-600',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-fuchsia-700 dark:hover:bg-fuchsia-600',
                'focus'    => 'focus:ring-2 focus:ring-fuchsia-400 focus:ring-offset-2 dark:focus:ring-fuchsia-300',
                'active'   => 'active:bg-fuchsia-800 dark:active:bg-fuchsia-700',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'slate' => [
                'bg'       => 'bg-slate-600 dark:bg-slate-600',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-slate-700 dark:hover:bg-slate-600',
                'focus'    => 'focus:ring-2 focus:ring-slate-400 focus:ring-offset-2 dark:focus:ring-slate-300',
                'active'   => 'active:bg-slate-800 dark:active:bg-slate-700',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'stone' => [
                'bg'       => 'bg-stone-600 dark:bg-stone-600',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-stone-700 dark:hover:bg-stone-600',
                'focus'    => 'focus:ring-2 focus:ring-stone-400 focus:ring-offset-2 dark:focus:ring-stone-300',
                'active'   => 'active:bg-stone-800 dark:active:bg-stone-700',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'zinc' => [
                'bg'       => 'bg-zinc-600 dark:bg-zinc-600',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-zinc-700 dark:hover:bg-zinc-600',
                'focus'    => 'focus:ring-2 focus:ring-zinc-400 focus:ring-offset-2 dark:focus:ring-zinc-300',
                'active'   => 'active:bg-zinc-800 dark:active:bg-zinc-700',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'neutral' => [
                'bg'       => 'bg-neutral-600 dark:bg-neutral-600',
                'text'     => 'text-white',
                'border'   => 'border-transparent dark:ring-offset-black',
                'hover'    => 'hover:bg-neutral-700 dark:hover:bg-neutral-600',
                'focus'    => 'focus:ring-2 focus:ring-neutral-400 focus:ring-offset-2 dark:focus:ring-neutral-300',
                'active'   => 'active:bg-neutral-800 dark:active:bg-neutral-700',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
        ],

        'soft' => [
            'beartropy' => [
                'bg'       => 'bg-beartropy-200 dark:bg-beartropy-800/40',
                'text'     => 'text-beartropy-700 dark:text-beartropy-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-beartropy-100 dark:hover:bg-beartropy-900/40',
                'focus'    => 'focus:ring-2 focus:ring-beartropy-300 focus:ring-offset-2 focus:outline-none focus:bg-beartropy-100 dark:focus:ring-beartropy-900/40 dark:focus:bg-beartropy-900/40',
                'active'   => 'active:bg-beartropy-200 dark:active:bg-beartropy-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'red' => [
                'bg'       => 'bg-red-200 dark:bg-red-800/40',
                'text'     => 'text-red-700 dark:text-red-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-red-100 dark:hover:bg-red-900/40',
                'focus'    => 'focus:ring-2 focus:ring-red-300 focus:ring-offset-2 focus:outline-none focus:bg-red-100 dark:focus:ring-red-900/40 dark:focus:bg-red-900/40',
                'active'   => 'active:bg-red-200 dark:active:bg-red-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'blue' => [
                'bg'       => 'bg-blue-200 dark:bg-blue-800/40',
                'text'     => 'text-blue-700 dark:text-blue-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-blue-100 dark:hover:bg-blue-900/40',
                'focus'    => 'focus:ring-2 focus:ring-blue-300 focus:ring-offset-2 focus:outline-none focus:bg-blue-100 dark:focus:ring-blue-900/40 dark:focus:bg-blue-900/40',
                'active'   => 'active:bg-blue-200 dark:active:bg-blue-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'green' => [
                'bg'       => 'bg-green-200 dark:bg-green-800/40',
                'text'     => 'text-green-700 dark:text-green-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-green-100 dark:hover:bg-green-900/40',
                'focus'    => 'focus:ring-2 focus:ring-green-300 focus:ring-offset-2 focus:outline-none focus:bg-green-100 dark:focus:ring-green-900/40 dark:focus:bg-green-900/40',
                'active'   => 'active:bg-green-200 dark:active:bg-green-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'yellow' => [
                'bg'       => 'bg-yellow-200 dark:bg-yellow-800/40',
                'text'     => 'text-yellow-700 dark:text-yellow-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-yellow-100 dark:hover:bg-yellow-900/40',
                'focus'    => 'focus:ring-2 focus:ring-yellow-300 focus:ring-offset-2 focus:outline-none focus:bg-yellow-100 dark:focus:ring-yellow-900/40 dark:focus:bg-yellow-900/40',
                'active'   => 'active:bg-yellow-200 dark:active:bg-yellow-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'purple' => [
                'bg'       => 'bg-purple-200 dark:bg-purple-800/40',
                'text'     => 'text-purple-700 dark:text-purple-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-purple-100 dark:hover:bg-purple-900/40',
                'focus'    => 'focus:ring-2 focus:ring-purple-300 focus:ring-offset-2 focus:outline-none focus:bg-purple-100 dark:focus:ring-purple-900/40 dark:focus:bg-purple-900/40',
                'active'   => 'active:bg-purple-200 dark:active:bg-purple-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'pink' => [
                'bg'       => 'bg-pink-200 dark:bg-pink-800/40',
                'text'     => 'text-pink-700 dark:text-pink-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-pink-100 dark:hover:bg-pink-900/40',
                'focus'    => 'focus:ring-2 focus:ring-pink-300 focus:ring-offset-2 focus:outline-none focus:bg-pink-100 dark:focus:ring-pink-900/40 dark:focus:bg-pink-900/40',
                'active'   => 'active:bg-pink-200 dark:active:bg-pink-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'gray' => [
                'bg'       => 'bg-gray-200 dark:bg-gray-800/40',
                'text'     => 'text-gray-700 dark:text-gray-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-gray-100 dark:hover:bg-gray-900/40',
                'focus'    => 'focus:ring-2 focus:ring-gray-300 focus:ring-offset-2 focus:outline-none focus:bg-gray-100 dark:focus:ring-gray-900/40 dark:focus:bg-gray-900/40',
                'active'   => 'active:bg-gray-200 dark:active:bg-gray-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'orange' => [
                'bg'       => 'bg-orange-200 dark:bg-orange-800/40',
                'text'     => 'text-orange-700 dark:text-orange-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-orange-100 dark:hover:bg-orange-900/40',
                'focus'    => 'focus:ring-2 focus:ring-orange-300 focus:ring-offset-2 focus:outline-none focus:bg-orange-100 dark:focus:ring-orange-900/40 dark:focus:bg-orange-900/40',
                'active'   => 'active:bg-orange-200 dark:active:bg-orange-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'amber' => [
                'bg'       => 'bg-amber-200 dark:bg-amber-800/40',
                'text'     => 'text-amber-700 dark:text-amber-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-amber-100 dark:hover:bg-amber-900/40',
                'focus'    => 'focus:ring-2 focus:ring-amber-300 focus:ring-offset-2 focus:outline-none focus:bg-amber-100 dark:focus:ring-amber-900/40 dark:focus:bg-amber-900/40',
                'active'   => 'active:bg-amber-200 dark:active:bg-amber-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'lime' => [
                'bg'       => 'bg-lime-200 dark:bg-lime-800/40',
                'text'     => 'text-lime-700 dark:text-lime-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-lime-100 dark:hover:bg-lime-900/40',
                'focus'    => 'focus:ring-2 focus:ring-lime-300 focus:ring-offset-2 focus:outline-none focus:bg-lime-100 dark:focus:ring-lime-900/40 dark:focus:bg-lime-900/40',
                'active'   => 'active:bg-lime-200 dark:active:bg-lime-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'emerald' => [
                'bg'       => 'bg-emerald-200 dark:bg-emerald-800/40',
                'text'     => 'text-emerald-700 dark:text-emerald-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-emerald-100 dark:hover:bg-emerald-900/40',
                'focus'    => 'focus:ring-2 focus:ring-emerald-300 focus:ring-offset-2 focus:outline-none focus:bg-emerald-100 dark:focus:ring-emerald-900/40 dark:focus:bg-emerald-900/40',
                'active'   => 'active:bg-emerald-200 dark:active:bg-emerald-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'teal' => [
                'bg'       => 'bg-teal-200 dark:bg-teal-800/40',
                'text'     => 'text-teal-700 dark:text-teal-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-teal-100 dark:hover:bg-teal-900/40',
                'focus'    => 'focus:ring-2 focus:ring-teal-300 focus:ring-offset-2 focus:outline-none focus:bg-teal-100 dark:focus:ring-teal-900/40 dark:focus:bg-teal-900/40',
                'active'   => 'active:bg-teal-200 dark:active:bg-teal-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'cyan' => [
                'bg'       => 'bg-cyan-200 dark:bg-cyan-800/40',
                'text'     => 'text-cyan-700 dark:text-cyan-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-cyan-100 dark:hover:bg-cyan-900/40',
                'focus'    => 'focus:ring-2 focus:ring-cyan-300 focus:ring-offset-2 focus:outline-none focus:bg-cyan-100 dark:focus:ring-cyan-900/40 dark:focus:bg-cyan-900/40',
                'active'   => 'active:bg-cyan-200 dark:active:bg-cyan-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'sky' => [
                'bg'       => 'bg-sky-200 dark:bg-sky-800/40',
                'text'     => 'text-sky-700 dark:text-sky-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-sky-100 dark:hover:bg-sky-900/40',
                'focus'    => 'focus:ring-2 focus:ring-sky-300 focus:ring-offset-2 focus:outline-none focus:bg-sky-100 dark:focus:ring-sky-900/40 dark:focus:bg-sky-900/40',
                'active'   => 'active:bg-sky-200 dark:active:bg-sky-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'indigo' => [
                'bg'       => 'bg-indigo-200 dark:bg-indigo-800/40',
                'text'     => 'text-indigo-700 dark:text-indigo-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-indigo-100 dark:hover:bg-indigo-900/40',
                'focus'    => 'focus:ring-2 focus:ring-indigo-300 focus:ring-offset-2 focus:outline-none focus:bg-indigo-100 dark:focus:ring-indigo-900/40 dark:focus:bg-indigo-900/40',
                'active'   => 'active:bg-indigo-200 dark:active:bg-indigo-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'violet' => [
                'bg'       => 'bg-violet-200 dark:bg-violet-800/40',
                'text'     => 'text-violet-700 dark:text-violet-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-violet-100 dark:hover:bg-violet-900/40',
                'focus'    => 'focus:ring-2 focus:ring-violet-300 focus:ring-offset-2 focus:outline-none focus:bg-violet-100 dark:focus:ring-violet-900/40 dark:focus:bg-violet-900/40',
                'active'   => 'active:bg-violet-200 dark:active:bg-violet-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'rose' => [
                'bg'       => 'bg-rose-200 dark:bg-rose-800/40',
                'text'     => 'text-rose-700 dark:text-rose-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-rose-100 dark:hover:bg-rose-900/40',
                'focus'    => 'focus:ring-2 focus:ring-rose-300 focus:ring-offset-2 focus:outline-none focus:bg-rose-100 dark:focus:ring-rose-900/40 dark:focus:bg-rose-900/40',
                'active'   => 'active:bg-rose-200 dark:active:bg-rose-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'fuchsia' => [
                'bg'       => 'bg-fuchsia-200 dark:bg-fuchsia-800/40',
                'text'     => 'text-fuchsia-700 dark:text-fuchsia-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-fuchsia-100 dark:hover:bg-fuchsia-900/40',
                'focus'    => 'focus:ring-2 focus:ring-fuchsia-300 focus:ring-offset-2 focus:outline-none focus:bg-fuchsia-100 dark:focus:ring-fuchsia-900/40 dark:focus:bg-fuchsia-900/40',
                'active'   => 'active:bg-fuchsia-200 dark:active:bg-fuchsia-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'slate' => [
                'bg'       => 'bg-slate-200 dark:bg-slate-800/40',
                'text'     => 'text-slate-700 dark:text-slate-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-slate-100 dark:hover:bg-slate-900/40',
                'focus'    => 'focus:ring-2 focus:ring-slate-300 focus:ring-offset-2 focus:outline-none focus:bg-slate-100 dark:focus:ring-slate-900/40 dark:focus:bg-slate-900/40',
                'active'   => 'active:bg-slate-200 dark:active:bg-slate-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'stone' => [
                'bg'       => 'bg-stone-200 dark:bg-stone-800/40',
                'text'     => 'text-stone-700 dark:text-stone-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-stone-100 dark:hover:bg-stone-900/40',
                'focus'    => 'focus:ring-2 focus:ring-stone-300 focus:ring-offset-2 focus:outline-none focus:bg-stone-100 dark:focus:ring-stone-900/40 dark:focus:bg-stone-900/40',
                'active'   => 'active:bg-stone-200 dark:active:bg-stone-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'zinc' => [
                'bg'       => 'bg-zinc-200 dark:bg-zinc-800/40',
                'text'     => 'text-zinc-700 dark:text-zinc-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-zinc-100 dark:hover:bg-zinc-900/40',
                'focus'    => 'focus:ring-2 focus:ring-zinc-300 focus:ring-offset-2 focus:outline-none focus:bg-zinc-100 dark:focus:ring-zinc-900/40 dark:focus:bg-zinc-900/40',
                'active'   => 'active:bg-zinc-200 dark:active:bg-zinc-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'neutral' => [
                'bg'       => 'bg-neutral-200 dark:bg-neutral-800/40',
                'text'     => 'text-neutral-700 dark:text-neutral-200',
                'border'   => 'border-none dark:ring-offset-black',
                'hover'    => 'hover:bg-neutral-100 dark:hover:bg-neutral-900/40',
                'focus'    => 'focus:ring-2 focus:ring-neutral-300 focus:ring-offset-2 focus:outline-none focus:bg-neutral-100 dark:focus:ring-neutral-900/40 dark:focus:bg-neutral-900/40',
                'active'   => 'active:bg-neutral-200 dark:active:bg-neutral-900/60',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
        ],

        'outline' => [
            'beartropy' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-gray-600 dark:text-gray-400/70',
                'border'   => 'border border-gray-300 dark:border-gray-700 dark:ring-offset-black',
                'hover'    => 'hover:bg-beartropy-100 dark:hover:bg-beartropy-500/20',
                'focus'    => 'focus:ring-2 focus:ring-beartropy-500 focus:ring-offset-01 focus:outline-none focus:bg-beartropy-100 dark:focus:ring-beartropy-500 dark:focus:bg-beartropy-800/20',
                'active'   => 'active:bg-beartropy-100 dark:active:bg-beartropy-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'red' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-red-600 dark:text-red-400/70',
                'border'   => 'border-red-600 dark:border-red-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-red-100 dark:hover:bg-red-500/20',
                'focus'    => 'focus:ring-2 focus:ring-red-400 focus:ring-offset-0 focus:outline-none focus:bg-red-100 dark:focus:ring-red-600/50 dark:focus:bg-red-700/20',
                'active'   => 'active:bg-red-100 dark:active:bg-red-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'blue' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-blue-600 dark:text-blue-400/70',
                'border'   => 'border-blue-600 dark:border-blue-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-blue-100 dark:hover:bg-blue-500/20',
                'focus'    => 'focus:ring-2 focus:ring-blue-400 focus:ring-offset-0 focus:outline-none focus:bg-blue-100 dark:focus:ring-blue-600/50 dark:focus:bg-blue-700/20',
                'active'   => 'active:bg-blue-100 dark:active:bg-blue-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'green' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-green-600 dark:text-green-400/70',
                'border'   => 'border-green-600 dark:border-green-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-green-100 dark:hover:bg-green-500/20',
                'focus'    => 'focus:ring-2 focus:ring-green-400 focus:ring-offset-0 focus:outline-none focus:bg-green-100 dark:focus:ring-green-600/50 dark:focus:bg-green-700/20',
                'active'   => 'active:bg-green-100 dark:active:bg-green-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'yellow' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-yellow-600 dark:text-yellow-400/70',
                'border'   => 'border-yellow-600 dark:border-yellow-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-yellow-100 dark:hover:bg-yellow-500/20',
                'focus'    => 'focus:ring-2 focus:ring-yellow-400 focus:ring-offset-0 focus:outline-none focus:bg-yellow-100 dark:focus:ring-yellow-600/50 dark:focus:bg-yellow-700/20',
                'active'   => 'active:bg-yellow-100 dark:active:bg-yellow-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'purple' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-purple-600 dark:text-purple-400/70',
                'border'   => 'border-purple-600 dark:border-purple-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-purple-100 dark:hover:bg-purple-500/20',
                'focus'    => 'focus:ring-2 focus:ring-purple-400 focus:ring-offset-0 focus:outline-none focus:bg-purple-100 dark:focus:ring-purple-600/50 dark:focus:bg-purple-700/20',
                'active'   => 'active:bg-purple-100 dark:active:bg-purple-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'pink' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-pink-600 dark:text-pink-400/70',
                'border'   => 'border-pink-600 dark:border-pink-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-pink-100 dark:hover:bg-pink-500/20',
                'focus'    => 'focus:ring-2 focus:ring-pink-400 focus:ring-offset-0 focus:outline-none focus:bg-pink-100 dark:focus:ring-pink-600/50 dark:focus:bg-pink-700/20',
                'active'   => 'active:bg-pink-100 dark:active:bg-pink-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'gray' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-gray-600 dark:text-gray-400/70',
                'border'   => 'border-gray-600 dark:border-gray-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-gray-100 dark:hover:bg-gray-500/20',
                'focus'    => 'focus:ring-2 focus:ring-gray-400 focus:ring-offset-0 focus:outline-none focus:bg-gray-100 dark:focus:ring-gray-600/50 dark:focus:bg-gray-700/20',
                'active'   => 'active:bg-gray-100 dark:active:bg-gray-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'orange' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-orange-600 dark:text-orange-400/70',
                'border'   => 'border-orange-600 dark:border-orange-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-orange-100 dark:hover:bg-orange-500/20',
                'focus'    => 'focus:ring-2 focus:ring-orange-400 focus:ring-offset-0 focus:outline-none focus:bg-orange-100 dark:focus:ring-orange-600/50 dark:focus:bg-orange-700/20',
                'active'   => 'active:bg-orange-100 dark:active:bg-orange-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'amber' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-amber-600 dark:text-amber-400/70',
                'border'   => 'border-amber-600 dark:border-amber-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-amber-100 dark:hover:bg-amber-500/20',
                'focus'    => 'focus:ring-2 focus:ring-amber-400 focus:ring-offset-0 focus:outline-none focus:bg-amber-100 dark:focus:ring-amber-600/50 dark:focus:bg-amber-700/20',
                'active'   => 'active:bg-amber-100 dark:active:bg-amber-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'lime' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-lime-600 dark:text-lime-400/70',
                'border'   => 'border-lime-600 dark:border-lime-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-lime-100 dark:hover:bg-lime-500/20',
                'focus'    => 'focus:ring-2 focus:ring-lime-400 focus:ring-offset-0 focus:outline-none focus:bg-lime-100 dark:focus:ring-lime-600/50 dark:focus:bg-lime-700/20',
                'active'   => 'active:bg-lime-100 dark:active:bg-lime-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'emerald' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-emerald-600 dark:text-emerald-400/70',
                'border'   => 'border-emerald-600 dark:border-emerald-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-emerald-100 dark:hover:bg-emerald-500/20',
                'focus'    => 'focus:ring-2 focus:ring-emerald-400 focus:ring-offset-0 focus:outline-none focus:bg-emerald-100 dark:focus:ring-emerald-600/50 dark:focus:bg-emerald-700/20',
                'active'   => 'active:bg-emerald-100 dark:active:bg-emerald-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'teal' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-teal-600 dark:text-teal-400/70',
                'border'   => 'border-teal-600 dark:border-teal-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-teal-100 dark:hover:bg-teal-500/20',
                'focus'    => 'focus:ring-2 focus:ring-teal-400 focus:ring-offset-0 focus:outline-none focus:bg-teal-100 dark:focus:ring-teal-600/50 dark:focus:bg-teal-700/20',
                'active'   => 'active:bg-teal-100 dark:active:bg-teal-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'cyan' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-cyan-600 dark:text-cyan-400/70',
                'border'   => 'border-cyan-600 dark:border-cyan-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-cyan-100 dark:hover:bg-cyan-500/20',
                'focus'    => 'focus:ring-2 focus:ring-cyan-400 focus:ring-offset-0 focus:outline-none focus:bg-cyan-100 dark:focus:ring-cyan-600/50 dark:focus:bg-cyan-700/20',
                'active'   => 'active:bg-cyan-100 dark:active:bg-cyan-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'sky' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-sky-600 dark:text-sky-400/70',
                'border'   => 'border-sky-600 dark:border-sky-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-sky-100 dark:hover:bg-sky-500/20',
                'focus'    => 'focus:ring-2 focus:ring-sky-400 focus:ring-offset-0 focus:outline-none focus:bg-sky-100 dark:focus:ring-sky-600/50 dark:focus:bg-sky-700/20',
                'active'   => 'active:bg-sky-100 dark:active:bg-sky-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'indigo' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-indigo-600 dark:text-indigo-400/70',
                'border'   => 'border-indigo-600 dark:border-indigo-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-indigo-100 dark:hover:bg-indigo-500/20',
                'focus'    => 'focus:ring-2 focus:ring-indigo-400 focus:ring-offset-0 focus:outline-none focus:bg-indigo-100 dark:focus:ring-indigo-600/50 dark:focus:bg-indigo-700/20',
                'active'   => 'active:bg-indigo-100 dark:active:bg-indigo-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'violet' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-violet-600 dark:text-violet-400/70',
                'border'   => 'border-violet-600 dark:border-violet-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-violet-100 dark:hover:bg-violet-500/20',
                'focus'    => 'focus:ring-2 focus:ring-violet-400 focus:ring-offset-0 focus:outline-none focus:bg-violet-100 dark:focus:ring-violet-600/50 dark:focus:bg-violet-700/20',
                'active'   => 'active:bg-violet-100 dark:active:bg-violet-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'rose' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-rose-600 dark:text-rose-400/70',
                'border'   => 'border-rose-600 dark:border-rose-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-rose-100 dark:hover:bg-rose-500/20',
                'focus'    => 'focus:ring-2 focus:ring-rose-400 focus:ring-offset-0 focus:outline-none focus:bg-rose-100 dark:focus:ring-rose-600/50 dark:focus:bg-rose-700/20',
                'active'   => 'active:bg-rose-100 dark:active:bg-rose-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'fuchsia' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-fuchsia-600 dark:text-fuchsia-400/70',
                'border'   => 'border-fuchsia-600 dark:border-fuchsia-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-fuchsia-100 dark:hover:bg-fuchsia-500/20',
                'focus'    => 'focus:ring-2 focus:ring-fuchsia-400 focus:ring-offset-0 focus:outline-none focus:bg-fuchsia-100 dark:focus:ring-fuchsia-600/50 dark:focus:bg-fuchsia-700/20',
                'active'   => 'active:bg-fuchsia-100 dark:active:bg-fuchsia-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'slate' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-slate-600 dark:text-slate-400/70',
                'border'   => 'border-slate-600 dark:border-slate-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-slate-100 dark:hover:bg-slate-500/20',
                'focus'    => 'focus:ring-2 focus:ring-slate-400 focus:ring-offset-0 focus:outline-none focus:bg-slate-100 dark:focus:ring-slate-600/50 dark:focus:bg-slate-700/20',
                'active'   => 'active:bg-slate-100 dark:active:bg-slate-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'stone' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-stone-600 dark:text-stone-400/70',
                'border'   => 'border-stone-600 dark:border-stone-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-stone-100 dark:hover:bg-stone-500/20',
                'focus'    => 'focus:ring-2 focus:ring-stone-400 focus:ring-offset-0 focus:outline-none focus:bg-stone-100 dark:focus:ring-stone-600/50 dark:focus:bg-stone-700/20',
                'active'   => 'active:bg-stone-100 dark:active:bg-stone-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'zinc' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-zinc-600 dark:text-zinc-400/70',
                'border'   => 'border-zinc-600 dark:border-zinc-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-zinc-100 dark:hover:bg-zinc-500/20',
                'focus'    => 'focus:ring-2 focus:ring-zinc-400 focus:ring-offset-0 focus:outline-none focus:bg-zinc-100 dark:focus:ring-zinc-600/50 dark:focus:bg-zinc-700/20',
                'active'   => 'active:bg-zinc-100 dark:active:bg-zinc-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'neutral' => [
                'bg'       => 'bg-transparent',
                'text'     => 'text-neutral-600 dark:text-neutral-400/70',
                'border'   => 'border-neutral-600 dark:border-neutral-600/50 dark:ring-offset-black',
                'hover'    => 'hover:bg-neutral-100 dark:hover:bg-neutral-500/20',
                'focus'    => 'focus:ring-2 focus:ring-neutral-400 focus:ring-offset-0 focus:outline-none focus:bg-neutral-100 dark:focus:ring-neutral-600/50 dark:focus:bg-neutral-700/20',
                'active'   => 'active:bg-neutral-100 dark:active:bg-neutral-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
        ],


        'ghost' => [
            'beartropy' => [
                'bg'       => '',
                'text'     => 'text-beartropy-600 dark:text-beartropy-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-beartropy-100 dark:hover:bg-beartropy-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-beartropy-400 focus:bg-beartropy-100 dark:focus:ring-beartropy-600/50 dark:focus:bg-beartropy-700/20',
                'active'   => 'active:bg-beartropy-100 dark:active:bg-beartropy-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'red' => [
                'bg'       => '',
                'text'     => 'text-red-600 dark:text-red-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-red-100 dark:hover:bg-red-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-red-400 focus:bg-red-100 dark:focus:ring-red-600/50 dark:focus:bg-red-700/20',
                'active'   => 'active:bg-red-100 dark:active:bg-red-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'blue' => [
                'bg'       => '',
                'text'     => 'text-blue-600 dark:text-blue-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-blue-100 dark:hover:bg-blue-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-blue-400 focus:bg-blue-100 dark:focus:ring-blue-600/50 dark:focus:bg-blue-700/20',
                'active'   => 'active:bg-blue-100 dark:active:bg-blue-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'green' => [
                'bg'       => '',
                'text'     => 'text-green-600 dark:text-green-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-green-100 dark:hover:bg-green-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-green-400 focus:bg-green-100 dark:focus:ring-green-600/50 dark:focus:bg-green-700/20',
                'active'   => 'active:bg-green-100 dark:active:bg-green-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'yellow' => [
                'bg'       => '',
                'text'     => 'text-yellow-600 dark:text-yellow-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-yellow-100 dark:hover:bg-yellow-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-yellow-400 focus:bg-yellow-100 dark:focus:ring-yellow-600/50 dark:focus:bg-yellow-700/20',
                'active'   => 'active:bg-yellow-100 dark:active:bg-yellow-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'purple' => [
                'bg'       => '',
                'text'     => 'text-purple-600 dark:text-purple-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-purple-100 dark:hover:bg-purple-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-purple-400 focus:bg-purple-100 dark:focus:ring-purple-600/50 dark:focus:bg-purple-700/20',
                'active'   => 'active:bg-purple-100 dark:active:bg-purple-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'pink' => [
                'bg'       => '',
                'text'     => 'text-pink-600 dark:text-pink-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-pink-100 dark:hover:bg-pink-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-pink-400 focus:bg-pink-100 dark:focus:ring-pink-600/50 dark:focus:bg-pink-700/20',
                'active'   => 'active:bg-pink-100 dark:active:bg-pink-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'gray' => [
                'bg'       => '',
                'text'     => 'text-gray-600 dark:text-gray-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-gray-100 dark:hover:bg-gray-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-gray-400 focus:bg-gray-100 dark:focus:ring-gray-600/50 dark:focus:bg-gray-700/20',
                'active'   => 'active:bg-gray-100 dark:active:bg-gray-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'orange' => [
                'bg'       => '',
                'text'     => 'text-orange-600 dark:text-orange-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-orange-100 dark:hover:bg-orange-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-orange-400 focus:bg-orange-100 dark:focus:ring-orange-600/50 dark:focus:bg-orange-700/20',
                'active'   => 'active:bg-orange-100 dark:active:bg-orange-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'amber' => [
                'bg'       => '',
                'text'     => 'text-amber-600 dark:text-amber-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-amber-100 dark:hover:bg-amber-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-amber-400 focus:bg-amber-100 dark:focus:ring-amber-600/50 dark:focus:bg-amber-700/20',
                'active'   => 'active:bg-amber-100 dark:active:bg-amber-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'lime' => [
                'bg'       => '',
                'text'     => 'text-lime-600 dark:text-lime-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-lime-100 dark:hover:bg-lime-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-lime-400 focus:bg-lime-100 dark:focus:ring-lime-600/50 dark:focus:bg-lime-700/20',
                'active'   => 'active:bg-lime-100 dark:active:bg-lime-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'emerald' => [
                'bg'       => '',
                'text'     => 'text-emerald-600 dark:text-emerald-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-emerald-100 dark:hover:bg-emerald-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-emerald-400 focus:bg-emerald-100 dark:focus:ring-emerald-600/50 dark:focus:bg-emerald-700/20',
                'active'   => 'active:bg-emerald-100 dark:active:bg-emerald-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'teal' => [
                'bg'       => '',
                'text'     => 'text-teal-600 dark:text-teal-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-teal-100 dark:hover:bg-teal-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-teal-400 focus:bg-teal-100 dark:focus:ring-teal-600/50 dark:focus:bg-teal-700/20',
                'active'   => 'active:bg-teal-100 dark:active:bg-teal-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'cyan' => [
                'bg'       => '',
                'text'     => 'text-cyan-600 dark:text-cyan-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-cyan-100 dark:hover:bg-cyan-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-cyan-400 focus:bg-cyan-100 dark:focus:ring-cyan-600/50 dark:focus:bg-cyan-700/20',
                'active'   => 'active:bg-cyan-100 dark:active:bg-cyan-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'sky' => [
                'bg'       => '',
                'text'     => 'text-sky-600 dark:text-sky-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-sky-100 dark:hover:bg-sky-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-sky-400 focus:bg-sky-100 dark:focus:ring-sky-600/50 dark:focus:bg-sky-700/20',
                'active'   => 'active:bg-sky-100 dark:active:bg-sky-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'indigo' => [
                'bg'       => '',
                'text'     => 'text-indigo-600 dark:text-indigo-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-indigo-100 dark:hover:bg-indigo-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-indigo-400 focus:bg-indigo-100 dark:focus:ring-indigo-600/50 dark:focus:bg-indigo-700/20',
                'active'   => 'active:bg-indigo-100 dark:active:bg-indigo-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'violet' => [
                'bg'       => '',
                'text'     => 'text-violet-600 dark:text-violet-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-violet-100 dark:hover:bg-violet-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-violet-400 focus:bg-violet-100 dark:focus:ring-violet-600/50 dark:focus:bg-violet-700/20',
                'active'   => 'active:bg-violet-100 dark:active:bg-violet-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'rose' => [
                'bg'       => '',
                'text'     => 'text-rose-600 dark:text-rose-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-rose-100 dark:hover:bg-rose-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-rose-400 focus:bg-rose-100 dark:focus:ring-rose-600/50 dark:focus:bg-rose-700/20',
                'active'   => 'active:bg-rose-100 dark:active:bg-rose-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'fuchsia' => [
                'bg'       => '',
                'text'     => 'text-fuchsia-600 dark:text-fuchsia-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-fuchsia-100 dark:hover:bg-fuchsia-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-fuchsia-400 focus:bg-fuchsia-100 dark:focus:ring-fuchsia-600/50 dark:focus:bg-fuchsia-700/20',
                'active'   => 'active:bg-fuchsia-100 dark:active:bg-fuchsia-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'slate' => [
                'bg'       => '',
                'text'     => 'text-slate-600 dark:text-slate-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-slate-100 dark:hover:bg-slate-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-slate-400 focus:bg-slate-100 dark:focus:ring-slate-600/50 dark:focus:bg-slate-700/20',
                'active'   => 'active:bg-slate-100 dark:active:bg-slate-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'stone' => [
                'bg'       => '',
                'text'     => 'text-stone-600 dark:text-stone-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-stone-100 dark:hover:bg-stone-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-stone-400 focus:bg-stone-100 dark:focus:ring-stone-600/50 dark:focus:bg-stone-700/20',
                'active'   => 'active:bg-stone-100 dark:active:bg-stone-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'zinc' => [
                'bg'       => '',
                'text'     => 'text-zinc-600 dark:text-zinc-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-zinc-100 dark:hover:bg-zinc-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-zinc-400 focus:bg-zinc-100 dark:focus:ring-zinc-600/50 dark:focus:bg-zinc-700/20',
                'active'   => 'active:bg-zinc-100 dark:active:bg-zinc-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'neutral' => [
                'bg'       => '',
                'text'     => 'text-neutral-600 dark:text-neutral-400/70',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-neutral-100 dark:hover:bg-neutral-500/20',
                'focus'    => 'focus:ring-2 focus:outline-none focus:ring-neutral-400 focus:bg-neutral-100 dark:focus:ring-neutral-600/50 dark:focus:bg-neutral-700/20',
                'active'   => 'active:bg-neutral-100 dark:active:bg-neutral-700/20',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
        ],

        'tint' => [
            'beartropy' => [
                'bg'       => 'bg-beartropy-100 dark:bg-beartropy-900/30',
                'text'     => 'text-beartropy-700 dark:text-beartropy-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-beartropy-200 dark:hover:bg-beartropy-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'red' => [
                'bg'       => 'bg-red-100 dark:bg-red-900/30',
                'text'     => 'text-red-700 dark:text-red-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-red-200 dark:hover:bg-red-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'blue' => [
                'bg'       => 'bg-blue-100 dark:bg-blue-900/30',
                'text'     => 'text-blue-700 dark:text-blue-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-blue-200 dark:hover:bg-blue-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'green' => [
                'bg'       => 'bg-green-100 dark:bg-green-900/30',
                'text'     => 'text-green-700 dark:text-green-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-green-200 dark:hover:bg-green-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'yellow' => [
                'bg'       => 'bg-yellow-100 dark:bg-yellow-900/30',
                'text'     => 'text-yellow-700 dark:text-yellow-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-yellow-200 dark:hover:bg-yellow-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'purple' => [
                'bg'       => 'bg-purple-100 dark:bg-purple-900/30',
                'text'     => 'text-purple-700 dark:text-purple-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-purple-200 dark:hover:bg-purple-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'pink' => [
                'bg'       => 'bg-pink-100 dark:bg-pink-900/30',
                'text'     => 'text-pink-700 dark:text-pink-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-pink-200 dark:hover:bg-pink-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'gray' => [
                'bg'       => 'bg-gray-100 dark:bg-gray-900/30',
                'text'     => 'text-gray-700 dark:text-gray-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-gray-200 dark:hover:bg-gray-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'orange' => [
                'bg'       => 'bg-orange-100 dark:bg-orange-900/30',
                'text'     => 'text-orange-700 dark:text-orange-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-orange-200 dark:hover:bg-orange-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'amber' => [
                'bg'       => 'bg-amber-100 dark:bg-amber-900/30',
                'text'     => 'text-amber-700 dark:text-amber-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-amber-200 dark:hover:bg-amber-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'lime' => [
                'bg'       => 'bg-lime-100 dark:bg-lime-900/30',
                'text'     => 'text-lime-700 dark:text-lime-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-lime-200 dark:hover:bg-lime-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'emerald' => [
                'bg'       => 'bg-emerald-100 dark:bg-emerald-900/30',
                'text'     => 'text-emerald-700 dark:text-emerald-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-emerald-200 dark:hover:bg-emerald-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'teal' => [
                'bg'       => 'bg-teal-100 dark:bg-teal-900/30',
                'text'     => 'text-teal-700 dark:text-teal-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-teal-200 dark:hover:bg-teal-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'cyan' => [
                'bg'       => 'bg-cyan-100 dark:bg-cyan-900/30',
                'text'     => 'text-cyan-700 dark:text-cyan-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-cyan-200 dark:hover:bg-cyan-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'sky' => [
                'bg'       => 'bg-sky-100 dark:bg-sky-900/30',
                'text'     => 'text-sky-700 dark:text-sky-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-sky-200 dark:hover:bg-sky-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'indigo' => [
                'bg'       => 'bg-indigo-100 dark:bg-indigo-900/30',
                'text'     => 'text-indigo-700 dark:text-indigo-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-indigo-200 dark:hover:bg-indigo-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'violet' => [
                'bg'       => 'bg-violet-100 dark:bg-violet-900/30',
                'text'     => 'text-violet-700 dark:text-violet-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-violet-200 dark:hover:bg-violet-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'rose' => [
                'bg'       => 'bg-rose-100 dark:bg-rose-900/30',
                'text'     => 'text-rose-700 dark:text-rose-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-rose-200 dark:hover:bg-rose-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'fuchsia' => [
                'bg'       => 'bg-fuchsia-100 dark:bg-fuchsia-900/30',
                'text'     => 'text-fuchsia-700 dark:text-fuchsia-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-fuchsia-200 dark:hover:bg-fuchsia-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'slate' => [
                'bg'       => 'bg-slate-100 dark:bg-slate-900/30',
                'text'     => 'text-slate-700 dark:text-slate-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-slate-200 dark:hover:bg-slate-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'stone' => [
                'bg'       => 'bg-stone-100 dark:bg-stone-900/30',
                'text'     => 'text-stone-700 dark:text-stone-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-stone-200 dark:hover:bg-stone-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'zinc' => [
                'bg'       => 'bg-zinc-100 dark:bg-zinc-900/30',
                'text'     => 'text-zinc-700 dark:text-zinc-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-zinc-200 dark:hover:bg-zinc-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
            'neutral' => [
                'bg'       => 'bg-neutral-100 dark:bg-neutral-900/30',
                'text'     => 'text-neutral-700 dark:text-neutral-300',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-neutral-200 dark:hover:bg-neutral-900/50',
                'focus'    => '',
                'active'   => '',
                'disabled' => 'opacity-60 cursor-not-allowed'
            ],
        ],

        'glass' => [
            'beartropy' => [
                'bg'       => 'bg-beartropy-400/20',
                'text'     => 'text-beartropy-700 dark:text-beartropy-500',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-beartropy-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-beartropy-400/40 active:dark:bg-beartropy-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'red' => [
                'bg'       => 'bg-red-400/20',
                'text'     => 'text-red-700 dark:text-red-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-red-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-red-400/40 active:dark:bg-red-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'blue' => [
                'bg'       => 'bg-blue-400/20',
                'text'     => 'text-blue-700 dark:text-blue-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-blue-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-blue-400/40 active:dark:bg-blue-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'green' => [
                'bg'       => 'bg-green-400/20',
                'text'     => 'text-green-700 dark:text-green-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-green-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-green-400/40 active:dark:bg-green-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'yellow' => [
                'bg'       => 'bg-yellow-300/20',
                'text'     => 'text-yellow-800 dark:text-yellow-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-yellow-300/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-yellow-300/40 active:dark:bg-yellow-400/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'purple' => [
                'bg'       => 'bg-purple-400/20',
                'text'     => 'text-purple-700 dark:text-purple-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-purple-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-purple-400/40 active:dark:bg-purple-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'pink' => [
                'bg'       => 'bg-pink-400/20',
                'text'     => 'text-pink-700 dark:text-pink-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-pink-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-pink-400/40 active:dark:bg-pink-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'gray' => [
                'bg'       => 'bg-gray-400/20',
                'text'     => 'text-gray-700 dark:text-gray-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-gray-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-gray-400/40 active:dark:bg-gray-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'orange' => [
                'bg'       => 'bg-orange-400/20',
                'text'     => 'text-orange-700 dark:text-orange-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-orange-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-orange-400/40 active:dark:bg-orange-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'amber' => [
                'bg'       => 'bg-amber-300/20',
                'text'     => 'text-amber-800 dark:text-amber-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-amber-300/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-amber-300/40 active:dark:bg-amber-400/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'lime' => [
                'bg'       => 'bg-lime-300/20',
                'text'     => 'text-lime-800 dark:text-lime-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-lime-300/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-lime-300/40 active:dark:bg-lime-400/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'emerald' => [
                'bg'       => 'bg-emerald-400/20',
                'text'     => 'text-emerald-700 dark:text-emerald-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-emerald-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-emerald-400/40 active:dark:bg-emerald-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'teal' => [
                'bg'       => 'bg-teal-400/20',
                'text'     => 'text-teal-700 dark:text-teal-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-teal-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-teal-400/40 active:dark:bg-teal-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'cyan' => [
                'bg'       => 'bg-cyan-400/20',
                'text'     => 'text-cyan-700 dark:text-cyan-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-cyan-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-cyan-400/40 active:dark:bg-cyan-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'sky' => [
                'bg'       => 'bg-sky-400/20',
                'text'     => 'text-sky-700 dark:text-sky-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-sky-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-sky-400/40 active:dark:bg-sky-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'indigo' => [
                'bg'       => 'bg-indigo-400/20',
                'text'     => 'text-indigo-700 dark:text-indigo-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-indigo-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-indigo-400/40 active:dark:bg-indigo-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'violet' => [
                'bg'       => 'bg-violet-400/20',
                'text'     => 'text-violet-700 dark:text-violet-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-violet-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-violet-400/40 active:dark:bg-violet-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'rose' => [
                'bg'       => 'bg-rose-400/20',
                'text'     => 'text-rose-700 dark:text-rose-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-rose-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-rose-400/40 active:dark:bg-rose-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'fuchsia' => [
                'bg'       => 'bg-fuchsia-400/20',
                'text'     => 'text-fuchsia-700 dark:text-fuchsia-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-fuchsia-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-fuchsia-400/40 active:dark:bg-fuchsia-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'slate' => [
                'bg'       => 'bg-slate-400/20',
                'text'     => 'text-slate-700 dark:text-slate-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-slate-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-slate-400/40 active:dark:bg-slate-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'stone' => [
                'bg'       => 'bg-stone-400/20',
                'text'     => 'text-stone-700 dark:text-stone-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-stone-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-stone-400/40 active:dark:bg-stone-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'zinc' => [
                'bg'       => 'bg-zinc-400/20',
                'text'     => 'text-zinc-700 dark:text-zinc-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-zinc-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-zinc-400/40 active:dark:bg-zinc-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'neutral' => [
                'bg'       => 'bg-neutral-400/20',
                'text'     => 'text-neutral-700 dark:text-neutral-400',
                'border'   => 'border-none',
                'hover'    => 'hover:bg-neutral-400/30 backdrop-blur-md',
                'focus'    => '',
                'active'   => 'active:bg-neutral-400/40 active:dark:bg-neutral-500/30',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
        ],

        'gradient' => [
            'beartropy' => [
                'bg'       => 'bg-gradient-to-r from-beartropy-500 via-cyan-500 to-teal-400 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-beartropy-500/60 active:bg-beartropy-500/60 active:text-beartropy-700 dark:active:bg-beartropy-600/50 dark:active:text-beartropy-400',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'red' => [
                'bg'       => 'bg-gradient-to-r from-red-500 via-pink-500 to-yellow-400 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-red-500/60 active:bg-red-500/60 active:text-red-700 dark:active:bg-red-600/50 dark:active:text-red-400',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'blue' => [
                'bg'       => 'bg-gradient-to-r from-blue-500 via-cyan-500 to-sky-400 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-blue-500/60 active:bg-blue-500/60 active:text-blue-700 dark:active:bg-blue-600/50 dark:active:text-blue-400',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'green' => [
                'bg'       => 'bg-gradient-to-r from-green-500 via-lime-400 to-emerald-400 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-green-500/60 active:bg-green-500/60 active:text-green-700 dark:active:bg-green-600/50 dark:active:text-green-400',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'yellow' => [
                'bg'       => 'bg-gradient-to-r from-yellow-400 via-amber-400 to-orange-400 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-neutral-900 text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-yellow-400/60 active:bg-yellow-400/60 active:text-yellow-700 dark:active:bg-yellow-500/50 dark:active:text-yellow-300',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'purple' => [
                'bg'       => 'bg-gradient-to-r from-purple-500 via-fuchsia-500 to-indigo-400 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-purple-500/60 active:bg-purple-500/60 active:text-purple-700 dark:active:bg-purple-600/50 dark:active:text-purple-400',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'pink' => [
                'bg'       => 'bg-gradient-to-r from-pink-500 via-rose-400 to-fuchsia-400 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-pink-500/60 active:bg-pink-500/60 active:text-pink-700 dark:active:bg-pink-600/50 dark:active:text-pink-400',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'gray' => [
                'bg'       => 'bg-gradient-to-r from-gray-500 via-slate-400 to-stone-400 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-gray-500/60 active:bg-gray-500/60 active:text-gray-700 dark:active:bg-gray-600/50 dark:active:text-gray-400',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'orange' => [
                'bg'       => 'bg-gradient-to-r from-orange-500 via-amber-400 to-yellow-300 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-orange-500/60 active:bg-orange-500/60 active:text-orange-700 dark:active:bg-orange-600/50 dark:active:text-orange-400',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'amber' => [
                'bg'       => 'bg-gradient-to-r from-amber-400 via-yellow-400 to-orange-300 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-neutral-900 text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-amber-400/60 active:bg-amber-400/60 active:text-amber-700 dark:active:bg-amber-500/50 dark:active:text-amber-300',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'lime' => [
                'bg'       => 'bg-gradient-to-r from-lime-400 via-green-400 to-emerald-300 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-neutral-900 text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-lime-400/60 active:bg-lime-400/60 active:text-lime-700 dark:active:bg-lime-500/50 dark:active:text-lime-300',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'emerald' => [
                'bg'       => 'bg-gradient-to-r from-emerald-400 via-teal-400 to-lime-300 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-emerald-400/60 active:bg-emerald-400/60 active:text-emerald-700 dark:active:bg-emerald-500/50 dark:active:text-emerald-300',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'teal' => [
                'bg'       => 'bg-gradient-to-r from-teal-400 via-cyan-400 to-blue-400 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-teal-400/60 active:bg-teal-400/60 active:text-teal-700 dark:active:bg-teal-500/50 dark:active:text-teal-300',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'cyan' => [
                'bg'       => 'bg-gradient-to-r from-cyan-400 via-blue-400 to-sky-300 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-cyan-400/60 active:bg-cyan-400/60 active:text-cyan-700 dark:active:bg-cyan-500/50 dark:active:text-cyan-300',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'sky' => [
                'bg'       => 'bg-gradient-to-r from-sky-400 via-cyan-400 to-blue-300 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-sky-400/60 active:bg-sky-400/60 active:text-sky-700 dark:active:bg-sky-500/50 dark:active:text-sky-300',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'indigo' => [
                'bg'       => 'bg-gradient-to-r from-indigo-500 via-purple-400 to-blue-400 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-indigo-500/60 active:bg-indigo-500/60 active:text-indigo-700 dark:active:bg-indigo-600/50 dark:active:text-indigo-400',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'violet' => [
                'bg'       => 'bg-gradient-to-r from-violet-500 via-indigo-400 to-purple-400 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-violet-500/60 active:bg-violet-500/60 active:text-violet-700 dark:active:bg-violet-600/50 dark:active:text-violet-400',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'rose' => [
                'bg'       => 'bg-gradient-to-r from-rose-500 via-pink-400 to-fuchsia-400 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-rose-500/60 active:bg-rose-500/60 active:text-rose-700 dark:active:bg-rose-600/50 dark:active:text-rose-400',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'fuchsia' => [
                'bg'       => 'bg-gradient-to-r from-fuchsia-400 via-pink-400 to-purple-400 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-fuchsia-400/60 active:bg-fuchsia-400/60 active:text-fuchsia-700 dark:active:bg-fuchsia-500/50 dark:active:text-fuchsia-300',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'slate' => [
                'bg'       => 'bg-gradient-to-r from-slate-400 via-zinc-400 to-gray-300 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-slate-400/60 active:bg-slate-400/60 active:text-slate-700 dark:active:bg-slate-500/50 dark:active:text-slate-300',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'stone' => [
                'bg'       => 'bg-gradient-to-r from-stone-400 via-zinc-400 to-neutral-300 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-stone-400/60 active:bg-stone-400/60 active:text-stone-700 dark:active:bg-stone-500/50 dark:active:text-stone-300',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'zinc' => [
                'bg'       => 'bg-gradient-to-r from-zinc-400 via-neutral-400 to-gray-300 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-zinc-400/60 active:bg-zinc-400/60 active:text-zinc-700 dark:active:bg-zinc-500/50 dark:active:text-zinc-300',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
            'neutral' => [
                'bg'       => 'bg-gradient-to-r from-neutral-400 via-zinc-400 to-stone-300 px-8 shadow-lg transition-transform !rounded-full',
                'text'     => 'text-white text-lg font-semibold',
                'border'   => 'border-none',
                'hover'    => 'hover:scale-105',
                'focus'    => '',
                'active'   => 'active:ring-2 active:ring-neutral-400/60 active:bg-neutral-400/60 active:text-neutral-700 dark:active:bg-neutral-500/50 dark:active:text-neutral-300',
                'disabled' => 'opacity-60 cursor-not-allowed',
            ],
        ],

    ],
];