<?php

return [
    'colors' => [
        'beartropy' => [
            'wrapper' => 'relative bg-gray-300/50 dark:bg-gray-900 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-gray-700 dark:text-gray-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'placeholder:text-gray-400 w-full border-none !outline-none bg-transparent py-2 px-3 text-gray-800 dark:text-gray-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-4 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-gray-200 dark:border-gray-700/50 shadow-sm focus-within:ring-2 focus-within:ring-gray-200 dark:focus-within:ring-gray-700',
        ],
        'red' => [
            'wrapper' => 'relative bg-red-300/50 dark:bg-red-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-red-700 dark:text-red-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-red-800 dark:text-red-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-red-300 dark:border-red-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'blue' => [
            'wrapper' => 'relative bg-blue-300/50 dark:bg-blue-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-blue-700 dark:text-blue-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-blue-800 dark:text-blue-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-blue-300 dark:border-blue-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'green' => [
            'wrapper' => 'relative bg-green-300/50 dark:bg-green-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-green-700 dark:text-green-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-green-800 dark:text-green-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-green-300 dark:border-green-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'yellow' => [
            'wrapper' => 'relative bg-yellow-300/50 dark:bg-yellow-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-yellow-700 dark:text-yellow-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-yellow-800 dark:text-yellow-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-yellow-300 dark:border-yellow-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'purple' => [
            'wrapper' => 'relative bg-purple-300/50 dark:bg-purple-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-purple-700 dark:text-purple-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-purple-800 dark:text-purple-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-purple-300 dark:border-purple-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'pink' => [
            'wrapper' => 'relative bg-pink-300/50 dark:bg-pink-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-pink-700 dark:text-pink-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-pink-800 dark:text-pink-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-pink-300 dark:border-pink-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'gray' => [
            'wrapper' => 'relative bg-gray-300/50 dark:bg-gray-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-gray-700 dark:text-gray-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-gray-800 dark:text-gray-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-gray-300 dark:border-gray-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'orange' => [
            'wrapper' => 'relative bg-orange-300/50 dark:bg-orange-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-orange-700 dark:text-orange-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-orange-800 dark:text-orange-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-orange-300 dark:border-orange-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'amber' => [
            'wrapper' => 'relative bg-amber-300/50 dark:bg-amber-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-amber-700 dark:text-amber-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-amber-800 dark:text-amber-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-amber-300 dark:border-amber-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'lime' => [
            'wrapper' => 'relative bg-lime-300/50 dark:bg-lime-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-lime-700 dark:text-lime-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-lime-800 dark:text-lime-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-lime-300 dark:border-lime-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'emerald' => [
            'wrapper' => 'relative bg-emerald-300/50 dark:bg-emerald-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-emerald-700 dark:text-emerald-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-emerald-800 dark:text-emerald-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-emerald-300 dark:border-emerald-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'teal' => [
            'wrapper' => 'relative bg-teal-300/50 dark:bg-teal-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-teal-700 dark:text-teal-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-teal-800 dark:text-teal-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-teal-300 dark:border-teal-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'cyan' => [
            'wrapper' => 'relative bg-cyan-300/50 dark:bg-cyan-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-cyan-700 dark:text-cyan-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-cyan-800 dark:text-cyan-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-cyan-300 dark:border-cyan-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'sky' => [
            'wrapper' => 'relative bg-sky-300/50 dark:bg-sky-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-sky-700 dark:text-sky-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-sky-800 dark:text-sky-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-sky-300 dark:border-sky-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'indigo' => [
            'wrapper' => 'relative bg-indigo-300/50 dark:bg-indigo-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-indigo-700 dark:text-indigo-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-indigo-800 dark:text-indigo-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-indigo-300 dark:border-indigo-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'violet' => [
            'wrapper' => 'relative bg-violet-300/50 dark:bg-violet-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-violet-700 dark:text-violet-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-violet-800 dark:text-violet-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-violet-300 dark:border-violet-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'rose' => [
            'wrapper' => 'relative bg-rose-300/50 dark:bg-rose-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-rose-700 dark:text-rose-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-rose-800 dark:text-rose-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-rose-300 dark:border-rose-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'fuchsia' => [
            'wrapper' => 'relative bg-fuchsia-300/50 dark:bg-fuchsia-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-fuchsia-700 dark:text-fuchsia-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-fuchsia-800 dark:text-fuchsia-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-fuchsia-300 dark:border-fuchsia-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'slate' => [
            'wrapper' => 'relative bg-slate-300/50 dark:bg-slate-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-slate-700 dark:text-slate-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-slate-800 dark:text-slate-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-slate-300 dark:border-slate-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'stone' => [
            'wrapper' => 'relative bg-stone-300/50 dark:bg-stone-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-stone-700 dark:text-stone-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-stone-800 dark:text-stone-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-stone-300 dark:border-stone-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'zinc' => [
            'wrapper' => 'relative bg-zinc-300/50 dark:bg-zinc-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-zinc-700 dark:text-zinc-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-zinc-800 dark:text-zinc-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-zinc-300 dark:border-zinc-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'neutral' => [
            'wrapper' => 'relative bg-neutral-300/50 dark:bg-neutral-800 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-neutral-700 dark:text-neutral-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-neutral-800 dark:text-neutral-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-neutral-300 dark:border-neutral-700 shadow-sm focus-within:ring-2 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
        ],
        'white' => [
            'wrapper' => 'relative bg-white dark:bg-zinc-900 rounded-[2rem] transition overflow-hidden p-1.5',
            'wrapper_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-zinc-700 dark:text-zinc-300/80 text-sm tracking-wide ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide ml-1',
            'input' => 'w-full border-none !outline-none bg-transparent py-2 px-3 text-zinc-800 dark:text-zinc-100 min-h-0 resize-none overflow-hidden max-h-60 mr-1',
            'footer' => 'px-3 pb-2 pt-1 flex items-center justify-between',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
            'border' => 'border border-zinc-200 dark:border-zinc-800 shadow-sm focus-within:ring-2 focus-within:ring-zinc-200 dark:focus-within:ring-zinc-700',
        ],
    ],
];
