<?php

return [
    'colors' => [
        'beartropy' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-beartropy-50 dark:hover:bg-beartropy-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-beartropy-100 dark:bg-beartropy-800',
            'option_selected' => 'bg-beartropy-200 dark:bg-beartropy-700 font-bold',
            'option_range' => 'bg-beartropy-100 dark:bg-beartropy-300/50',
            'today_ring' => 'ring-2 ring-beartropy-400 dark:ring-beartropy-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-beartropy-500 focus:border-beartropy-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-beartropy-500 text-white font-bold hover:bg-beartropy-600 dark:hover:bg-beartropy-600',
        ],
        'red' => [
            'dropdown_bg' => 'bg-red-100/80 dark:bg-red-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-red-50 dark:hover:bg-red-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-red-100 dark:bg-red-800',
            'option_selected' => 'bg-red-200 dark:bg-red-700 font-bold',
            'option_range' => 'bg-red-100 dark:bg-red-300/50',
            'today_ring' => 'ring-2 ring-red-400 dark:ring-red-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-red-500 focus:border-red-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-red-500 text-white font-bold hover:bg-red-600 dark:hover:bg-red-600',
        ],
        'blue' => [
            'dropdown_bg' => 'bg-blue-100/80 dark:bg-blue-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-blue-50 dark:hover:bg-blue-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-blue-100 dark:bg-blue-800',
            'option_selected' => 'bg-blue-200 dark:bg-blue-700 font-bold',
            'option_range' => 'bg-blue-100 dark:bg-blue-300/50',
            'today_ring' => 'ring-2 ring-blue-400 dark:ring-blue-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-blue-500 text-white font-bold hover:bg-blue-600 dark:hover:bg-blue-600',
        ],
        'green' => [
            'dropdown_bg' => 'bg-green-100/80 dark:bg-green-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-green-50 dark:hover:bg-green-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-green-100 dark:bg-green-800',
            'option_selected' => 'bg-green-200 dark:bg-green-700 font-bold',
            'option_range' => 'bg-green-100 dark:bg-green-300/50',
            'today_ring' => 'ring-2 ring-green-400 dark:ring-green-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-green-500 focus:border-green-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-green-500 text-white font-bold hover:bg-green-600 dark:hover:bg-green-600',
        ],
        'yellow' => [
            'dropdown_bg' => 'bg-yellow-100/80 dark:bg-yellow-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-yellow-50 dark:hover:bg-yellow-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-yellow-100 dark:bg-yellow-800',
            'option_selected' => 'bg-yellow-200 dark:bg-yellow-700 font-bold',
            'option_range' => 'bg-yellow-100 dark:bg-yellow-300/50',
            'today_ring' => 'ring-2 ring-yellow-400 dark:ring-yellow-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-yellow-500 text-white font-bold hover:bg-yellow-600 dark:hover:bg-yellow-600',
        ],
        'purple' => [
            'dropdown_bg' => 'bg-purple-100/80 dark:bg-purple-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-purple-50 dark:hover:bg-purple-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-purple-100 dark:bg-purple-800',
            'option_selected' => 'bg-purple-200 dark:bg-purple-700 font-bold',
            'option_range' => 'bg-purple-100 dark:bg-purple-300/50',
            'today_ring' => 'ring-2 ring-purple-400 dark:ring-purple-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-purple-500 text-white font-bold hover:bg-purple-600 dark:hover:bg-purple-600',
        ],
        'pink' => [
            'dropdown_bg' => 'bg-pink-100/80 dark:bg-pink-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-pink-50 dark:hover:bg-pink-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-pink-100 dark:bg-pink-800',
            'option_selected' => 'bg-pink-200 dark:bg-pink-700 font-bold',
            'option_range' => 'bg-pink-100 dark:bg-pink-300/50',
            'today_ring' => 'ring-2 ring-pink-400 dark:ring-pink-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-pink-500 focus:border-pink-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-pink-500 text-white font-bold hover:bg-pink-600 dark:hover:bg-pink-600',
        ],
        'gray' => [
            'dropdown_bg' => 'bg-gray-100/80 dark:bg-gray-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-gray-50 dark:hover:bg-gray-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-gray-100 dark:bg-gray-800',
            'option_selected' => 'bg-gray-200 dark:bg-gray-700 font-bold',
            'option_range' => 'bg-gray-100 dark:bg-gray-300/50',
            'today_ring' => 'ring-2 ring-gray-400 dark:ring-gray-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-gray-500 focus:border-gray-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-gray-500 text-white font-bold hover:bg-gray-600 dark:hover:bg-gray-600',
        ],
        'orange' => [
            'dropdown_bg' => 'bg-orange-100/80 dark:bg-orange-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-orange-50 dark:hover:bg-orange-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-orange-100 dark:bg-orange-800',
            'option_selected' => 'bg-orange-200 dark:bg-orange-700 font-bold',
            'option_range' => 'bg-orange-100 dark:bg-orange-300/50',
            'today_ring' => 'ring-2 ring-orange-400 dark:ring-orange-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-orange-500 focus:border-orange-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-orange-500 text-white font-bold hover:bg-orange-600 dark:hover:bg-orange-600',
        ],
        'amber' => [
            'dropdown_bg' => 'bg-amber-100/80 dark:bg-amber-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-amber-50 dark:hover:bg-amber-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-amber-100 dark:bg-amber-800',
            'option_selected' => 'bg-amber-200 dark:bg-amber-700 font-bold',
            'option_range' => 'bg-amber-100 dark:bg-amber-300/50',
            'today_ring' => 'ring-2 ring-amber-400 dark:ring-amber-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-amber-500 focus:border-amber-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-amber-500 text-white font-bold hover:bg-amber-600 dark:hover:bg-amber-600',
        ],
        'lime' => [
            'dropdown_bg' => 'bg-lime-100/80 dark:bg-lime-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-lime-50 dark:hover:bg-lime-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-lime-100 dark:bg-lime-800',
            'option_selected' => 'bg-lime-200 dark:bg-lime-700 font-bold',
            'option_range' => 'bg-lime-100 dark:bg-lime-300/50',
            'today_ring' => 'ring-2 ring-lime-400 dark:ring-lime-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-lime-500 focus:border-lime-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-lime-500 text-white font-bold hover:bg-lime-600 dark:hover:bg-lime-600',
        ],
        'emerald' => [
            'dropdown_bg' => 'bg-emerald-100/80 dark:bg-emerald-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-emerald-50 dark:hover:bg-emerald-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-emerald-100 dark:bg-emerald-800',
            'option_selected' => 'bg-emerald-200 dark:bg-emerald-700 font-bold',
            'option_range' => 'bg-emerald-100 dark:bg-emerald-300/50',
            'today_ring' => 'ring-2 ring-emerald-400 dark:ring-emerald-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-emerald-500 text-white font-bold hover:bg-emerald-600 dark:hover:bg-emerald-600',
        ],
        'teal' => [
            'dropdown_bg' => 'bg-teal-100/80 dark:bg-teal-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-teal-50 dark:hover:bg-teal-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-teal-100 dark:bg-teal-800',
            'option_selected' => 'bg-teal-200 dark:bg-teal-700 font-bold',
            'option_range' => 'bg-teal-100 dark:bg-teal-300/50',
            'today_ring' => 'ring-2 ring-teal-400 dark:ring-teal-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-teal-500 focus:border-teal-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-teal-500 text-white font-bold hover:bg-teal-600 dark:hover:bg-teal-600',
        ],
        'cyan' => [
            'dropdown_bg' => 'bg-cyan-100/80 dark:bg-cyan-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-cyan-50 dark:hover:bg-cyan-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-cyan-100 dark:bg-cyan-800',
            'option_selected' => 'bg-cyan-200 dark:bg-cyan-700 font-bold',
            'option_range' => 'bg-cyan-100 dark:bg-cyan-300/50',
            'today_ring' => 'ring-2 ring-cyan-400 dark:ring-cyan-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-cyan-500 text-white font-bold hover:bg-cyan-600 dark:hover:bg-cyan-600',
        ],
        'sky' => [
            'dropdown_bg' => 'bg-sky-100/80 dark:bg-sky-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-sky-50 dark:hover:bg-sky-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-sky-100 dark:bg-sky-800',
            'option_selected' => 'bg-sky-200 dark:bg-sky-700 font-bold',
            'option_range' => 'bg-sky-100 dark:bg-sky-300/50',
            'today_ring' => 'ring-2 ring-sky-400 dark:ring-sky-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-sky-500 focus:border-sky-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-sky-500 text-white font-bold hover:bg-sky-600 dark:hover:bg-sky-600',
        ],
        'indigo' => [
            'dropdown_bg' => 'bg-indigo-100/80 dark:bg-indigo-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-indigo-50 dark:hover:bg-indigo-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-indigo-100 dark:bg-indigo-800',
            'option_selected' => 'bg-indigo-200 dark:bg-indigo-700 font-bold',
            'option_range' => 'bg-indigo-100 dark:bg-indigo-300/50',
            'today_ring' => 'ring-2 ring-indigo-400 dark:ring-indigo-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-indigo-500 text-white font-bold hover:bg-indigo-600 dark:hover:bg-indigo-600',
        ],
        'violet' => [
            'dropdown_bg' => 'bg-violet-100/80 dark:bg-violet-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-violet-50 dark:hover:bg-violet-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-violet-100 dark:bg-violet-800',
            'option_selected' => 'bg-violet-200 dark:bg-violet-700 font-bold',
            'option_range' => 'bg-violet-100 dark:bg-violet-300/50',
            'today_ring' => 'ring-2 ring-violet-400 dark:ring-violet-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-violet-500 focus:border-violet-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-violet-500 text-white font-bold hover:bg-violet-600 dark:hover:bg-violet-600',
        ],
        'rose' => [
            'dropdown_bg' => 'bg-rose-100/80 dark:bg-rose-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-rose-50 dark:hover:bg-rose-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-rose-100 dark:bg-rose-800',
            'option_selected' => 'bg-rose-200 dark:bg-rose-700 font-bold',
            'option_range' => 'bg-rose-100 dark:bg-rose-300/50',
            'today_ring' => 'ring-2 ring-rose-400 dark:ring-rose-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-rose-500 focus:border-rose-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-rose-500 text-white font-bold hover:bg-rose-600 dark:hover:bg-rose-600',
        ],
        'fuchsia' => [
            'dropdown_bg' => 'bg-fuchsia-100/80 dark:bg-fuchsia-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-fuchsia-50 dark:hover:bg-fuchsia-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-fuchsia-100 dark:bg-fuchsia-800',
            'option_selected' => 'bg-fuchsia-200 dark:bg-fuchsia-700 font-bold',
            'option_range' => 'bg-fuchsia-100 dark:bg-fuchsia-300/50',
            'today_ring' => 'ring-2 ring-fuchsia-400 dark:ring-fuchsia-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-fuchsia-500 focus:border-fuchsia-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-fuchsia-500 text-white font-bold hover:bg-fuchsia-600 dark:hover:bg-fuchsia-600',
        ],
        'slate' => [
            'dropdown_bg' => 'bg-slate-100/80 dark:bg-slate-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-slate-50 dark:hover:bg-slate-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-slate-100 dark:bg-slate-800',
            'option_selected' => 'bg-slate-200 dark:bg-slate-700 font-bold',
            'option_range' => 'bg-slate-100 dark:bg-slate-300/50',
            'today_ring' => 'ring-2 ring-slate-400 dark:ring-slate-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-slate-500 focus:border-slate-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-slate-500 text-white font-bold hover:bg-slate-600 dark:hover:bg-slate-600',
        ],
        'stone' => [
            'dropdown_bg' => 'bg-stone-100/80 dark:bg-stone-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-stone-50 dark:hover:bg-stone-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-stone-100 dark:bg-stone-800',
            'option_selected' => 'bg-stone-200 dark:bg-stone-700 font-bold',
            'option_range' => 'bg-stone-100 dark:bg-stone-300/50',
            'today_ring' => 'ring-2 ring-stone-400 dark:ring-stone-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-stone-500 focus:border-stone-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-stone-500 text-white font-bold hover:bg-stone-600 dark:hover:bg-stone-600',
        ],
        'zinc' => [
            'dropdown_bg' => 'bg-zinc-100/80 dark:bg-zinc-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-zinc-50 dark:hover:bg-zinc-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-zinc-100 dark:bg-zinc-800',
            'option_selected' => 'bg-zinc-200 dark:bg-zinc-700 font-bold',
            'option_range' => 'bg-zinc-100 dark:bg-zinc-300/50',
            'today_ring' => 'ring-2 ring-zinc-400 dark:ring-zinc-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-zinc-500 focus:border-zinc-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-zinc-500 text-white font-bold hover:bg-zinc-600 dark:hover:bg-zinc-600',
        ],
        'neutral' => [
            'dropdown_bg' => 'bg-neutral-100/80 dark:bg-neutral-900/80',
            'dropdown_shadow' => 'shadow-xl',
            'border' => 'border border-neutral-200 dark:border-neutral-700',
            'header_text' => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
            'weekday_text' => 'text-neutral-500 dark:text-neutral-400',
            'grid_bg' => 'bg-transparent',
            'option_text' => 'text-neutral-800 dark:text-neutral-100',
            'option_hover' => 'hover:bg-neutral-50 dark:hover:bg-neutral-900/50 hover:rounded-none',
            'option_active' => 'font-bold bg-neutral-100 dark:bg-neutral-800',
            'option_selected' => 'bg-neutral-200 dark:bg-neutral-700 font-bold',
            'option_range' => 'bg-neutral-100 dark:bg-neutral-300/50',
            'today_ring' => 'ring-2 ring-neutral-400 dark:ring-neutral-700',
            'select' => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-neutral-500 focus:border-neutral-500 transition',
            'trigger_text' => 'text-neutral-800 dark:text-neutral-100',
            'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
            // List UI for time selection
            'list_column' => 'flex flex-col max-h-32 overflow-y-auto beartropy-thin-scrollbar w-16 text-center scroll-smooth',
            'list_item' => 'py-1 px-2 cursor-pointer rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-sm text-gray-700 dark:text-gray-300 transition-colors',
            'list_item_active' => 'bg-neutral-500 text-white font-bold hover:bg-neutral-600 dark:hover:bg-neutral-600',
        ],
    ],
];
