<?php

$shared = [
    'dropdown_bg'      => 'bg-white dark:bg-gray-900',
    'dropdown_shadow'  => 'shadow-xl',
    'header_text'      => 'text-lg font-semibold text-neutral-800 dark:text-neutral-200',
    'weekday_text'     => 'text-neutral-500 dark:text-neutral-400',
    'grid_bg'          => 'bg-transparent',
    'option_text'      => 'text-neutral-800 dark:text-neutral-100',
    'trigger_text'     => 'text-neutral-800 dark:text-neutral-100',
    'placeholder_text' => 'text-neutral-400 dark:text-neutral-500',
    'column_label'     => 'text-[11px] font-semibold uppercase tracking-wider text-gray-400 dark:text-gray-500',
    'wheel_adjacent'   => 'text-gray-300 dark:text-gray-600 hover:text-gray-400 dark:hover:text-gray-500',
];

$colors = [
    'beartropy' => array_merge($shared, [
        'dropdown_border' => 'border border-gray-300 dark:border-gray-600',
        'option_hover'    => 'hover:bg-beartropy-50 dark:hover:bg-beartropy-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-beartropy-100 dark:bg-beartropy-800',
        'option_selected' => 'bg-beartropy-200 dark:bg-beartropy-700 font-bold',
        'option_range'    => 'bg-beartropy-100 dark:bg-beartropy-800/50',
        'today_ring'      => 'ring-2 ring-beartropy-400 dark:ring-beartropy-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-beartropy-500 focus:border-beartropy-500 transition',
        'wheel_selected'  => 'text-beartropy-600 dark:text-beartropy-400',
        'wheel_highlight' => 'bg-beartropy-50 dark:bg-beartropy-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-beartropy-500 dark:text-beartropy-400 hover:text-beartropy-600 dark:hover:text-beartropy-300',
    ]),
    'red' => array_merge($shared, [
        'dropdown_border' => 'border border-red-300 dark:border-red-600',
        'option_hover'    => 'hover:bg-red-50 dark:hover:bg-red-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-red-100 dark:bg-red-800',
        'option_selected' => 'bg-red-200 dark:bg-red-700 font-bold',
        'option_range'    => 'bg-red-100 dark:bg-red-800/50',
        'today_ring'      => 'ring-2 ring-red-400 dark:ring-red-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-red-500 focus:border-red-500 transition',
        'wheel_selected'  => 'text-red-600 dark:text-red-400',
        'wheel_highlight' => 'bg-red-50 dark:bg-red-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-red-500 dark:text-red-400 hover:text-red-600 dark:hover:text-red-300',
    ]),
    'orange' => array_merge($shared, [
        'dropdown_border' => 'border border-orange-300 dark:border-orange-600',
        'option_hover'    => 'hover:bg-orange-50 dark:hover:bg-orange-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-orange-100 dark:bg-orange-800',
        'option_selected' => 'bg-orange-200 dark:bg-orange-700 font-bold',
        'option_range'    => 'bg-orange-100 dark:bg-orange-800/50',
        'today_ring'      => 'ring-2 ring-orange-400 dark:ring-orange-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-orange-500 focus:border-orange-500 transition',
        'wheel_selected'  => 'text-orange-600 dark:text-orange-400',
        'wheel_highlight' => 'bg-orange-50 dark:bg-orange-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-orange-500 dark:text-orange-400 hover:text-orange-600 dark:hover:text-orange-300',
    ]),
    'amber' => array_merge($shared, [
        'dropdown_border' => 'border border-amber-300 dark:border-amber-600',
        'option_hover'    => 'hover:bg-amber-50 dark:hover:bg-amber-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-amber-100 dark:bg-amber-800',
        'option_selected' => 'bg-amber-200 dark:bg-amber-700 font-bold',
        'option_range'    => 'bg-amber-100 dark:bg-amber-800/50',
        'today_ring'      => 'ring-2 ring-amber-400 dark:ring-amber-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-amber-500 focus:border-amber-500 transition',
        'wheel_selected'  => 'text-amber-600 dark:text-amber-400',
        'wheel_highlight' => 'bg-amber-50 dark:bg-amber-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-amber-500 dark:text-amber-400 hover:text-amber-600 dark:hover:text-amber-300',
    ]),
    'yellow' => array_merge($shared, [
        'dropdown_border' => 'border border-yellow-300 dark:border-yellow-600',
        'option_hover'    => 'hover:bg-yellow-50 dark:hover:bg-yellow-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-yellow-100 dark:bg-yellow-800',
        'option_selected' => 'bg-yellow-200 dark:bg-yellow-700 font-bold',
        'option_range'    => 'bg-yellow-100 dark:bg-yellow-800/50',
        'today_ring'      => 'ring-2 ring-yellow-400 dark:ring-yellow-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-yellow-500 focus:border-yellow-500 transition',
        'wheel_selected'  => 'text-yellow-600 dark:text-yellow-400',
        'wheel_highlight' => 'bg-yellow-50 dark:bg-yellow-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-yellow-500 dark:text-yellow-400 hover:text-yellow-600 dark:hover:text-yellow-300',
    ]),
    'lime' => array_merge($shared, [
        'dropdown_border' => 'border border-lime-300 dark:border-lime-600',
        'option_hover'    => 'hover:bg-lime-50 dark:hover:bg-lime-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-lime-100 dark:bg-lime-800',
        'option_selected' => 'bg-lime-200 dark:bg-lime-700 font-bold',
        'option_range'    => 'bg-lime-100 dark:bg-lime-800/50',
        'today_ring'      => 'ring-2 ring-lime-400 dark:ring-lime-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-lime-500 focus:border-lime-500 transition',
        'wheel_selected'  => 'text-lime-600 dark:text-lime-400',
        'wheel_highlight' => 'bg-lime-50 dark:bg-lime-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-lime-500 dark:text-lime-400 hover:text-lime-600 dark:hover:text-lime-300',
    ]),
    'green' => array_merge($shared, [
        'dropdown_border' => 'border border-green-300 dark:border-green-600',
        'option_hover'    => 'hover:bg-green-50 dark:hover:bg-green-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-green-100 dark:bg-green-800',
        'option_selected' => 'bg-green-200 dark:bg-green-700 font-bold',
        'option_range'    => 'bg-green-100 dark:bg-green-800/50',
        'today_ring'      => 'ring-2 ring-green-400 dark:ring-green-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-green-500 focus:border-green-500 transition',
        'wheel_selected'  => 'text-green-600 dark:text-green-400',
        'wheel_highlight' => 'bg-green-50 dark:bg-green-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-green-500 dark:text-green-400 hover:text-green-600 dark:hover:text-green-300',
    ]),
    'emerald' => array_merge($shared, [
        'dropdown_border' => 'border border-emerald-300 dark:border-emerald-600',
        'option_hover'    => 'hover:bg-emerald-50 dark:hover:bg-emerald-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-emerald-100 dark:bg-emerald-800',
        'option_selected' => 'bg-emerald-200 dark:bg-emerald-700 font-bold',
        'option_range'    => 'bg-emerald-100 dark:bg-emerald-800/50',
        'today_ring'      => 'ring-2 ring-emerald-400 dark:ring-emerald-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 transition',
        'wheel_selected'  => 'text-emerald-600 dark:text-emerald-400',
        'wheel_highlight' => 'bg-emerald-50 dark:bg-emerald-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-emerald-500 dark:text-emerald-400 hover:text-emerald-600 dark:hover:text-emerald-300',
    ]),
    'teal' => array_merge($shared, [
        'dropdown_border' => 'border border-teal-300 dark:border-teal-600',
        'option_hover'    => 'hover:bg-teal-50 dark:hover:bg-teal-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-teal-100 dark:bg-teal-800',
        'option_selected' => 'bg-teal-200 dark:bg-teal-700 font-bold',
        'option_range'    => 'bg-teal-100 dark:bg-teal-800/50',
        'today_ring'      => 'ring-2 ring-teal-400 dark:ring-teal-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-teal-500 focus:border-teal-500 transition',
        'wheel_selected'  => 'text-teal-600 dark:text-teal-400',
        'wheel_highlight' => 'bg-teal-50 dark:bg-teal-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-teal-500 dark:text-teal-400 hover:text-teal-600 dark:hover:text-teal-300',
    ]),
    'cyan' => array_merge($shared, [
        'dropdown_border' => 'border border-cyan-300 dark:border-cyan-600',
        'option_hover'    => 'hover:bg-cyan-50 dark:hover:bg-cyan-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-cyan-100 dark:bg-cyan-800',
        'option_selected' => 'bg-cyan-200 dark:bg-cyan-700 font-bold',
        'option_range'    => 'bg-cyan-100 dark:bg-cyan-800/50',
        'today_ring'      => 'ring-2 ring-cyan-400 dark:ring-cyan-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-cyan-500 focus:border-cyan-500 transition',
        'wheel_selected'  => 'text-cyan-600 dark:text-cyan-400',
        'wheel_highlight' => 'bg-cyan-50 dark:bg-cyan-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-cyan-500 dark:text-cyan-400 hover:text-cyan-600 dark:hover:text-cyan-300',
    ]),
    'sky' => array_merge($shared, [
        'dropdown_border' => 'border border-sky-300 dark:border-sky-600',
        'option_hover'    => 'hover:bg-sky-50 dark:hover:bg-sky-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-sky-100 dark:bg-sky-800',
        'option_selected' => 'bg-sky-200 dark:bg-sky-700 font-bold',
        'option_range'    => 'bg-sky-100 dark:bg-sky-800/50',
        'today_ring'      => 'ring-2 ring-sky-400 dark:ring-sky-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-sky-500 focus:border-sky-500 transition',
        'wheel_selected'  => 'text-sky-600 dark:text-sky-400',
        'wheel_highlight' => 'bg-sky-50 dark:bg-sky-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-sky-500 dark:text-sky-400 hover:text-sky-600 dark:hover:text-sky-300',
    ]),
    'blue' => array_merge($shared, [
        'dropdown_border' => 'border border-blue-300 dark:border-blue-600',
        'option_hover'    => 'hover:bg-blue-50 dark:hover:bg-blue-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-blue-100 dark:bg-blue-800',
        'option_selected' => 'bg-blue-200 dark:bg-blue-700 font-bold',
        'option_range'    => 'bg-blue-100 dark:bg-blue-800/50',
        'today_ring'      => 'ring-2 ring-blue-400 dark:ring-blue-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-blue-500 transition',
        'wheel_selected'  => 'text-blue-600 dark:text-blue-400',
        'wheel_highlight' => 'bg-blue-50 dark:bg-blue-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-blue-500 dark:text-blue-400 hover:text-blue-600 dark:hover:text-blue-300',
    ]),
    'indigo' => array_merge($shared, [
        'dropdown_border' => 'border border-indigo-300 dark:border-indigo-600',
        'option_hover'    => 'hover:bg-indigo-50 dark:hover:bg-indigo-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-indigo-100 dark:bg-indigo-800',
        'option_selected' => 'bg-indigo-200 dark:bg-indigo-700 font-bold',
        'option_range'    => 'bg-indigo-100 dark:bg-indigo-800/50',
        'today_ring'      => 'ring-2 ring-indigo-400 dark:ring-indigo-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 transition',
        'wheel_selected'  => 'text-indigo-600 dark:text-indigo-400',
        'wheel_highlight' => 'bg-indigo-50 dark:bg-indigo-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-indigo-500 dark:text-indigo-400 hover:text-indigo-600 dark:hover:text-indigo-300',
    ]),
    'violet' => array_merge($shared, [
        'dropdown_border' => 'border border-violet-300 dark:border-violet-600',
        'option_hover'    => 'hover:bg-violet-50 dark:hover:bg-violet-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-violet-100 dark:bg-violet-800',
        'option_selected' => 'bg-violet-200 dark:bg-violet-700 font-bold',
        'option_range'    => 'bg-violet-100 dark:bg-violet-800/50',
        'today_ring'      => 'ring-2 ring-violet-400 dark:ring-violet-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-violet-500 focus:border-violet-500 transition',
        'wheel_selected'  => 'text-violet-600 dark:text-violet-400',
        'wheel_highlight' => 'bg-violet-50 dark:bg-violet-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-violet-500 dark:text-violet-400 hover:text-violet-600 dark:hover:text-violet-300',
    ]),
    'purple' => array_merge($shared, [
        'dropdown_border' => 'border border-purple-300 dark:border-purple-600',
        'option_hover'    => 'hover:bg-purple-50 dark:hover:bg-purple-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-purple-100 dark:bg-purple-800',
        'option_selected' => 'bg-purple-200 dark:bg-purple-700 font-bold',
        'option_range'    => 'bg-purple-100 dark:bg-purple-800/50',
        'today_ring'      => 'ring-2 ring-purple-400 dark:ring-purple-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-purple-500 focus:border-purple-500 transition',
        'wheel_selected'  => 'text-purple-600 dark:text-purple-400',
        'wheel_highlight' => 'bg-purple-50 dark:bg-purple-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-purple-500 dark:text-purple-400 hover:text-purple-600 dark:hover:text-purple-300',
    ]),
    'fuchsia' => array_merge($shared, [
        'dropdown_border' => 'border border-fuchsia-300 dark:border-fuchsia-600',
        'option_hover'    => 'hover:bg-fuchsia-50 dark:hover:bg-fuchsia-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-fuchsia-100 dark:bg-fuchsia-800',
        'option_selected' => 'bg-fuchsia-200 dark:bg-fuchsia-700 font-bold',
        'option_range'    => 'bg-fuchsia-100 dark:bg-fuchsia-800/50',
        'today_ring'      => 'ring-2 ring-fuchsia-400 dark:ring-fuchsia-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-fuchsia-500 focus:border-fuchsia-500 transition',
        'wheel_selected'  => 'text-fuchsia-600 dark:text-fuchsia-400',
        'wheel_highlight' => 'bg-fuchsia-50 dark:bg-fuchsia-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-fuchsia-500 dark:text-fuchsia-400 hover:text-fuchsia-600 dark:hover:text-fuchsia-300',
    ]),
    'pink' => array_merge($shared, [
        'dropdown_border' => 'border border-pink-300 dark:border-pink-600',
        'option_hover'    => 'hover:bg-pink-50 dark:hover:bg-pink-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-pink-100 dark:bg-pink-800',
        'option_selected' => 'bg-pink-200 dark:bg-pink-700 font-bold',
        'option_range'    => 'bg-pink-100 dark:bg-pink-800/50',
        'today_ring'      => 'ring-2 ring-pink-400 dark:ring-pink-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-pink-500 focus:border-pink-500 transition',
        'wheel_selected'  => 'text-pink-600 dark:text-pink-400',
        'wheel_highlight' => 'bg-pink-50 dark:bg-pink-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-pink-500 dark:text-pink-400 hover:text-pink-600 dark:hover:text-pink-300',
    ]),
    'rose' => array_merge($shared, [
        'dropdown_border' => 'border border-rose-300 dark:border-rose-600',
        'option_hover'    => 'hover:bg-rose-50 dark:hover:bg-rose-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-rose-100 dark:bg-rose-800',
        'option_selected' => 'bg-rose-200 dark:bg-rose-700 font-bold',
        'option_range'    => 'bg-rose-100 dark:bg-rose-800/50',
        'today_ring'      => 'ring-2 ring-rose-400 dark:ring-rose-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-rose-500 focus:border-rose-500 transition',
        'wheel_selected'  => 'text-rose-600 dark:text-rose-400',
        'wheel_highlight' => 'bg-rose-50 dark:bg-rose-950/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-rose-500 dark:text-rose-400 hover:text-rose-600 dark:hover:text-rose-300',
    ]),
    'slate' => array_merge($shared, [
        'dropdown_border' => 'border border-slate-300 dark:border-slate-600',
        'option_hover'    => 'hover:bg-slate-50 dark:hover:bg-slate-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-slate-100 dark:bg-slate-800',
        'option_selected' => 'bg-slate-200 dark:bg-slate-700 font-bold',
        'option_range'    => 'bg-slate-100 dark:bg-slate-800/50',
        'today_ring'      => 'ring-2 ring-slate-400 dark:ring-slate-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-slate-500 focus:border-slate-500 transition',
        'wheel_selected'  => 'text-slate-700 dark:text-slate-300',
        'wheel_highlight' => 'bg-slate-100 dark:bg-slate-800/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-slate-500 dark:text-slate-400 hover:text-slate-600 dark:hover:text-slate-300',
    ]),
    'gray' => array_merge($shared, [
        'dropdown_border' => 'border border-gray-300 dark:border-gray-600',
        'option_hover'    => 'hover:bg-gray-50 dark:hover:bg-gray-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-gray-100 dark:bg-gray-800',
        'option_selected' => 'bg-gray-200 dark:bg-gray-700 font-bold',
        'option_range'    => 'bg-gray-100 dark:bg-gray-800/50',
        'today_ring'      => 'ring-2 ring-gray-400 dark:ring-gray-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-gray-500 focus:border-gray-500 transition',
        'wheel_selected'  => 'text-gray-700 dark:text-gray-300',
        'wheel_highlight' => 'bg-gray-100 dark:bg-gray-800/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-gray-500 dark:text-gray-400 hover:text-gray-600 dark:hover:text-gray-300',
    ]),
    'zinc' => array_merge($shared, [
        'dropdown_border' => 'border border-zinc-300 dark:border-zinc-600',
        'option_hover'    => 'hover:bg-zinc-50 dark:hover:bg-zinc-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-zinc-100 dark:bg-zinc-800',
        'option_selected' => 'bg-zinc-200 dark:bg-zinc-700 font-bold',
        'option_range'    => 'bg-zinc-100 dark:bg-zinc-800/50',
        'today_ring'      => 'ring-2 ring-zinc-400 dark:ring-zinc-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-zinc-500 focus:border-zinc-500 transition',
        'wheel_selected'  => 'text-zinc-700 dark:text-zinc-300',
        'wheel_highlight' => 'bg-zinc-100 dark:bg-zinc-800/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-zinc-500 dark:text-zinc-400 hover:text-zinc-600 dark:hover:text-zinc-300',
    ]),
    'neutral' => array_merge($shared, [
        'dropdown_border' => 'border border-neutral-300 dark:border-neutral-600',
        'option_hover'    => 'hover:bg-neutral-50 dark:hover:bg-neutral-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-neutral-100 dark:bg-neutral-800',
        'option_selected' => 'bg-neutral-200 dark:bg-neutral-700 font-bold',
        'option_range'    => 'bg-neutral-100 dark:bg-neutral-800/50',
        'today_ring'      => 'ring-2 ring-neutral-400 dark:ring-neutral-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-neutral-500 focus:border-neutral-500 transition',
        'wheel_selected'  => 'text-neutral-700 dark:text-neutral-300',
        'wheel_highlight' => 'bg-neutral-100 dark:bg-neutral-800/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-neutral-500 dark:text-neutral-400 hover:text-neutral-600 dark:hover:text-neutral-300',
    ]),
    'stone' => array_merge($shared, [
        'dropdown_border' => 'border border-stone-300 dark:border-stone-600',
        'option_hover'    => 'hover:bg-stone-50 dark:hover:bg-stone-900 hover:rounded-none',
        'option_active'   => 'font-bold bg-stone-100 dark:bg-stone-800',
        'option_selected' => 'bg-stone-200 dark:bg-stone-700 font-bold',
        'option_range'    => 'bg-stone-100 dark:bg-stone-800/50',
        'today_ring'      => 'ring-2 ring-stone-400 dark:ring-stone-500',
        'select'          => 'bg-white dark:bg-neutral-900 border border-gray-300 dark:border-gray-700 min-w-[3.5rem] text-gray-800 dark:text-gray-200 text-center h-9 rounded-xl focus:ring-2 focus:ring-stone-500 focus:border-stone-500 transition',
        'wheel_selected'  => 'text-stone-700 dark:text-stone-300',
        'wheel_highlight' => 'bg-stone-100 dark:bg-stone-800/30',
        'now_button'      => 'text-xs font-semibold tracking-wide uppercase cursor-pointer transition-colors duration-150 text-stone-500 dark:text-stone-400 hover:text-stone-600 dark:hover:text-stone-300',
    ]),
];

$colors['primary'] = $colors['beartropy'];

return ['colors' => $colors];
