<?php

return [
    'colors' => [
        'beartropy' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-neutral-300 dark:border-neutral-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-beartropy-50 dark:hover:bg-beartropy-900/95',
            'item_active_bg' => 'active:bg-beartropy-100 dark:active:bg-beartropy-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'red' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-red-300 dark:border-red-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-red-50 dark:hover:bg-red-900/95',
            'item_active_bg' => 'active:bg-red-100 dark:active:bg-red-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'neutral' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-neutral-400 dark:border-neutral-800',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-neutral-50 dark:hover:bg-neutral-900/95',
            'item_active_bg' => 'active:bg-neutral-100 dark:active:bg-neutral-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'green' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-green-300 dark:border-green-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-green-50 dark:hover:bg-green-900/95',
            'item_active_bg' => 'active:bg-green-100 dark:active:bg-green-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'blue' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-blue-300 dark:border-blue-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-blue-50 dark:hover:bg-blue-900/95',
            'item_active_bg' => 'active:bg-blue-100 dark:active:bg-blue-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'yellow' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-yellow-300 dark:border-yellow-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-yellow-50 dark:hover:bg-yellow-900/95',
            'item_active_bg' => 'active:bg-yellow-100 dark:active:bg-yellow-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'purple' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-purple-300 dark:border-purple-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-purple-50 dark:hover:bg-purple-900/95',
            'item_active_bg' => 'active:bg-purple-100 dark:active:bg-purple-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'pink' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-pink-300 dark:border-pink-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-pink-50 dark:hover:bg-pink-900/95',
            'item_active_bg' => 'active:bg-pink-100 dark:active:bg-pink-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'gray' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-gray-300 dark:border-gray-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-gray-50 dark:hover:bg-gray-900/95',
            'item_active_bg' => 'active:bg-gray-100 dark:active:bg-gray-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'orange' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-orange-300 dark:border-orange-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-orange-50 dark:hover:bg-orange-900/95',
            'item_active_bg' => 'active:bg-orange-100 dark:active:bg-orange-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'amber' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-amber-300 dark:border-amber-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-amber-50 dark:hover:bg-amber-900/95',
            'item_active_bg' => 'active:bg-amber-100 dark:active:bg-amber-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'lime' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-lime-300 dark:border-lime-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-lime-50 dark:hover:bg-lime-900/95',
            'item_active_bg' => 'active:bg-lime-100 dark:active:bg-lime-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'emerald' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-emerald-300 dark:border-emerald-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-emerald-50 dark:hover:bg-emerald-900/95',
            'item_active_bg' => 'active:bg-emerald-100 dark:active:bg-emerald-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'teal' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-teal-300 dark:border-teal-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-teal-50 dark:hover:bg-teal-900/95',
            'item_active_bg' => 'active:bg-teal-100 dark:active:bg-teal-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'cyan' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-cyan-300 dark:border-cyan-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-cyan-50 dark:hover:bg-cyan-900/95',
            'item_active_bg' => 'active:bg-cyan-100 dark:active:bg-cyan-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'sky' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-sky-300 dark:border-sky-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-sky-50 dark:hover:bg-sky-900/95',
            'item_active_bg' => 'active:bg-sky-100 dark:active:bg-sky-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'indigo' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-indigo-300 dark:border-indigo-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-indigo-50 dark:hover:bg-indigo-900/95',
            'item_active_bg' => 'active:bg-indigo-100 dark:active:bg-indigo-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'violet' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-violet-300 dark:border-violet-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-violet-50 dark:hover:bg-violet-900/95',
            'item_active_bg' => 'active:bg-violet-100 dark:active:bg-violet-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'rose' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-rose-300 dark:border-rose-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-rose-50 dark:hover:bg-rose-900/95',
            'item_active_bg' => 'active:bg-rose-100 dark:active:bg-rose-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'fuchsia' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-fuchsia-300 dark:border-fuchsia-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-fuchsia-50 dark:hover:bg-fuchsia-900/95',
            'item_active_bg' => 'active:bg-fuchsia-100 dark:active:bg-fuchsia-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'slate' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-slate-300 dark:border-slate-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-slate-50 dark:hover:bg-slate-900/95',
            'item_active_bg' => 'active:bg-slate-100 dark:active:bg-slate-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'stone' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-stone-300 dark:border-stone-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-stone-50 dark:hover:bg-stone-900/95',
            'item_active_bg' => 'active:bg-stone-100 dark:active:bg-stone-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
        'zinc' => [
            'dropdown_bg' => 'bg-white dark:bg-gray-900/95',
            'dropdown_border' => 'border border-zinc-300 dark:border-zinc-700',
            'dropdown_shadow' => 'shadow-lg',
            'item_hover_bg' => 'hover:bg-zinc-50 dark:hover:bg-zinc-900/95',
            'item_active_bg' => 'active:bg-zinc-100 dark:active:bg-zinc-800/95',
            'item_text_color' => 'text-neutral-700 dark:text-neutral-300',
            'item_disabled_text_color' => 'text-neutral-400 dark:text-neutral-600',
        ],
    ],
];
