<?php

return [
    'colors' => [
        'beartropy' => [
            'highlightParentText' => 'text-beartropy-600 dark:text-beartropy-400 font-bold',
            'highlightParentStandard' => 'bg-beartropy-200/60 dark:bg-beartropy-700/40 text-beartropy-700 dark:text-beartropy-300',
            'highlightChildText' => 'text-beartropy-500 dark:text-beartropy-400',
            'highlightChildStandard' => 'bg-beartropy-100/60 dark:bg-beartropy-800/40 text-beartropy-800 dark:text-beartropy-200',
            'hoverText' => 'hover:text-beartropy-500 dark:hover:text-beartropy-300',
            'hoverTextChild' => 'hover:text-beartropy-500 dark:hover:text-beartropy-300',
            'itemClassStandard' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition hover:bg-beartropy-200/40 dark:hover:bg-beartropy-600/30',
            'itemClassText' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition',
            'childItemClassStandard' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3 hover:bg-beartropy-100/40 dark:hover:bg-beartropy-800/30',
            'childItemClassText' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3',
            'childBorderClass' => 'border-l border-beartropy-500 dark:border-beartropy-400',
        ],
        'green' => [
            'highlightParentText' => 'text-green-600 dark:text-green-400 font-bold',
            'highlightParentStandard' => 'bg-green-200/60 dark:bg-green-700/40 text-green-700 dark:text-green-300',
            'highlightChildText' => 'text-green-500 dark:text-green-400',
            'highlightChildStandard' => 'bg-green-100/60 dark:bg-green-800/40 text-green-800 dark:text-green-200',
            'hoverText' => 'hover:text-green-500 dark:hover:text-green-300',
            'hoverTextChild' => 'hover:text-green-500 dark:hover:text-green-300',
            'itemClassStandard' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition hover:bg-green-200/40 dark:hover:bg-green-600/30',
            'itemClassText' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition',
            'childItemClassStandard' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3 hover:bg-green-100/40 dark:hover:bg-green-800/30',
            'childItemClassText' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3',
            'childBorderClass' => 'border-l border-green-500 dark:border-green-400',
        ],
        'blue' => [
            'highlightParentText' => 'text-blue-600 dark:text-blue-400 font-bold',
            'highlightParentStandard' => 'bg-blue-200/60 dark:bg-blue-700/40 text-blue-700 dark:text-blue-300',
            'highlightChildText' => 'text-blue-500 dark:text-blue-400',
            'highlightChildStandard' => 'bg-blue-100/60 dark:bg-blue-800/40 text-blue-800 dark:text-blue-200',
            'hoverText' => 'hover:text-blue-500 dark:hover:text-blue-300',
            'hoverTextChild' => 'hover:text-blue-500 dark:hover:text-blue-300',
            'itemClassStandard' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition hover:bg-blue-200/40 dark:hover:bg-blue-600/30',
            'itemClassText' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition',
            'childItemClassStandard' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3 hover:bg-blue-100/40 dark:hover:bg-blue-800/30',
            'childItemClassText' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3',
            'childBorderClass' => 'border-l border-blue-500 dark:border-blue-400',
        ],
        'violet' => [
            'highlightParentText' => 'text-violet-600 dark:text-violet-400 font-bold',
            'highlightParentStandard' => 'bg-violet-200/60 dark:bg-violet-700/40 text-violet-700 dark:text-violet-300',
            'highlightChildText' => 'text-violet-500 dark:text-violet-400',
            'highlightChildStandard' => 'bg-violet-100/60 dark:bg-violet-800/40 text-violet-800 dark:text-violet-200',
            'hoverText' => 'hover:text-violet-500 dark:hover:text-violet-300',
            'hoverTextChild' => 'hover:text-violet-500 dark:hover:text-violet-300',
            'itemClassStandard' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition hover:bg-violet-200/40 dark:hover:bg-violet-600/30',
            'itemClassText' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition',
            'childItemClassStandard' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3 hover:bg-violet-100/40 dark:hover:bg-violet-800/30',
            'childItemClassText' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3',
            'childBorderClass' => 'border-l border-violet-500 dark:border-violet-400',
        ],
        'red' => [
            'highlightParentText' => 'text-red-600 dark:text-red-400 font-bold',
            'highlightParentStandard' => 'bg-red-200/60 dark:bg-red-700/40 text-red-700 dark:text-red-300',
            'highlightChildText' => 'text-red-500 dark:text-red-400',
            'highlightChildStandard' => 'bg-red-100/60 dark:bg-red-800/40 text-red-800 dark:text-red-200',
            'hoverText' => 'hover:text-red-500 dark:hover:text-red-300',
            'hoverTextChild' => 'hover:text-red-500 dark:hover:text-red-300',
            'itemClassStandard' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition hover:bg-red-200/40 dark:hover:bg-red-600/30',
            'itemClassText' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition',
            'childItemClassStandard' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3 hover:bg-red-100/40 dark:hover:bg-red-800/30',
            'childItemClassText' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3',
            'childBorderClass' => 'border-l border-red-500 dark:border-red-400',
        ],
        'emerald' => [
            'highlightParentText' => 'text-emerald-600 dark:text-emerald-400 font-bold',
            'highlightParentStandard' => 'bg-emerald-200/60 dark:bg-emerald-700/40 text-emerald-700 dark:text-emerald-300',
            'highlightChildText' => 'text-emerald-500 dark:text-emerald-400',
            'highlightChildStandard' => 'bg-emerald-100/60 dark:bg-emerald-800/40 text-emerald-800 dark:text-emerald-200',
            'hoverText' => 'hover:text-emerald-500 dark:hover:text-emerald-300',
            'hoverTextChild' => 'hover:text-emerald-500 dark:hover:text-emerald-300',
            'itemClassStandard' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition hover:bg-emerald-200/40 dark:hover:bg-emerald-600/30',
            'itemClassText' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition',
            'childItemClassStandard' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3 hover:bg-emerald-100/40 dark:hover:bg-emerald-800/30',
            'childItemClassText' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3',
            'childBorderClass' => 'border-l border-emerald-500 dark:border-emerald-400',
        ],
        'yellow' => [
            'highlightParentText' => 'text-yellow-700 dark:text-yellow-300 font-bold',
            'highlightParentStandard' => 'bg-yellow-200/60 dark:bg-yellow-700/40 text-yellow-700 dark:text-yellow-300',
            'highlightChildText' => 'text-yellow-600 dark:text-yellow-300',
            'highlightChildStandard' => 'bg-yellow-100/60 dark:bg-yellow-800/40 text-yellow-800 dark:text-yellow-200',
            'hoverText' => 'hover:text-yellow-600 dark:hover:text-yellow-300',
            'hoverTextChild' => 'hover:text-yellow-600 dark:hover:text-yellow-300',
            'itemClassStandard' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition hover:bg-yellow-200/40 dark:hover:bg-yellow-600/30',
            'itemClassText' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition',
            'childItemClassStandard' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3 hover:bg-yellow-100/40 dark:hover:bg-yellow-800/30',
            'childItemClassText' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3',
            'childBorderClass' => 'border-l border-yellow-500 dark:border-yellow-400',
        ],
        'pink' => [
            'highlightParentText' => 'text-pink-600 dark:text-pink-400 font-bold',
            'highlightParentStandard' => 'bg-pink-200/60 dark:bg-pink-700/40 text-pink-700 dark:text-pink-300',
            'highlightChildText' => 'text-pink-500 dark:text-pink-400',
            'highlightChildStandard' => 'bg-pink-100/60 dark:bg-pink-800/40 text-pink-800 dark:text-pink-200',
            'hoverText' => 'hover:text-pink-500 dark:hover:text-pink-300',
            'hoverTextChild' => 'hover:text-pink-500 dark:hover:text-pink-300',
            'itemClassStandard' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition hover:bg-pink-200/40 dark:hover:bg-pink-600/30',
            'itemClassText' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition',
            'childItemClassStandard' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3 hover:bg-pink-100/40 dark:hover:bg-pink-800/30',
            'childItemClassText' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3',
            'childBorderClass' => 'border-l border-pink-500 dark:border-pink-400',
        ],
        'sky' => [
            'highlightParentText' => 'text-sky-600 dark:text-sky-400 font-bold',
            'highlightParentStandard' => 'bg-sky-200/60 dark:bg-sky-700/40 text-sky-700 dark:text-sky-300',
            'highlightChildText' => 'text-sky-500 dark:text-sky-400',
            'highlightChildStandard' => 'bg-sky-100/60 dark:bg-sky-800/40 text-sky-800 dark:text-sky-200',
            'hoverText' => 'hover:text-sky-500 dark:hover:text-sky-300',
            'hoverTextChild' => 'hover:text-sky-500 dark:hover:text-sky-300',
            'itemClassStandard' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition hover:bg-sky-200/40 dark:hover:bg-sky-600/30',
            'itemClassText' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition',
            'childItemClassStandard' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3 hover:bg-sky-100/40 dark:hover:bg-sky-800/30',
            'childItemClassText' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3',
            'childBorderClass' => 'border-l border-sky-500 dark:border-sky-400',
        ],
        'lime' => [
            'highlightParentText' => 'text-lime-600 dark:text-lime-400 font-bold',
            'highlightParentStandard' => 'bg-lime-200/60 dark:bg-lime-700/40 text-lime-700 dark:text-lime-300',
            'highlightChildText' => 'text-lime-500 dark:text-lime-400',
            'highlightChildStandard' => 'bg-lime-100/60 dark:bg-lime-800/40 text-lime-800 dark:text-lime-200',
            'hoverText' => 'hover:text-lime-500 dark:hover:text-lime-300',
            'hoverTextChild' => 'hover:text-lime-500 dark:hover:text-lime-300',
            'itemClassStandard' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition hover:bg-lime-200/40 dark:hover:bg-lime-600/30',
            'itemClassText' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition',
            'childItemClassStandard' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3 hover:bg-lime-100/40 dark:hover:bg-lime-800/30',
            'childItemClassText' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3',
            'childBorderClass' => 'border-l border-lime-500 dark:border-lime-400',
        ],
        'slate' => [
            'highlightParentText' => 'text-slate-600 dark:text-slate-300 font-bold',
            'highlightParentStandard' => 'bg-slate-200/60 dark:bg-slate-700/40 text-slate-700 dark:text-slate-300',
            'highlightChildText' => 'text-slate-500 dark:text-slate-300',
            'highlightChildStandard' => 'bg-slate-100/60 dark:bg-slate-800/40 text-slate-800 dark:text-slate-200',
            'hoverText' => 'hover:text-slate-600 dark:hover:text-slate-300',
            'hoverTextChild' => 'hover:text-slate-500 dark:hover:text-slate-300',
            'itemClassStandard' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition hover:bg-slate-200/40 dark:hover:bg-slate-600/30',
            'itemClassText' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition',
            'childItemClassStandard' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3 hover:bg-slate-100/40 dark:hover:bg-slate-800/30',
            'childItemClassText' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3',
            'childBorderClass' => 'border-l border-slate-500 dark:border-slate-400',
        ],
        'indigo' => [
            'highlightParentText' => 'text-indigo-600 dark:text-indigo-400 font-bold',
            'highlightParentStandard' => 'bg-indigo-200/60 dark:bg-indigo-700/40 text-indigo-700 dark:text-indigo-300',
            'highlightChildText' => 'text-indigo-500 dark:text-indigo-400',
            'highlightChildStandard' => 'bg-indigo-100/60 dark:bg-indigo-800/40 text-indigo-800 dark:text-indigo-200',
            'hoverText' => 'hover:text-indigo-500 dark:hover:text-indigo-300',
            'hoverTextChild' => 'hover:text-indigo-500 dark:hover:text-indigo-300',
            'itemClassStandard' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition hover:bg-indigo-200/40 dark:hover:bg-indigo-600/30',
            'itemClassText' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition',
            'childItemClassStandard' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3 hover:bg-indigo-100/40 dark:hover:bg-indigo-800/30',
            'childItemClassText' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3',
            'childBorderClass' => 'border-l border-indigo-500 dark:border-indigo-400',
        ],
        'fuchsia' => [
            'highlightParentText' => 'text-fuchsia-600 dark:text-fuchsia-400 font-bold',
            'highlightParentStandard' => 'bg-fuchsia-200/60 dark:bg-fuchsia-700/40 text-fuchsia-700 dark:text-fuchsia-300',
            'highlightChildText' => 'text-fuchsia-500 dark:text-fuchsia-400',
            'highlightChildStandard' => 'bg-fuchsia-100/60 dark:bg-fuchsia-800/40 text-fuchsia-800 dark:text-fuchsia-200',
            'hoverText' => 'hover:text-fuchsia-500 dark:hover:text-fuchsia-300',
            'hoverTextChild' => 'hover:text-fuchsia-500 dark:hover:text-fuchsia-300',
            'itemClassStandard' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition hover:bg-fuchsia-200/40 dark:hover:bg-fuchsia-600/30',
            'itemClassText' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition',
            'childItemClassStandard' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3 hover:bg-fuchsia-100/40 dark:hover:bg-fuchsia-800/30',
            'childItemClassText' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3',
            'childBorderClass' => 'border-l border-fuchsia-500 dark:border-fuchsia-400',
        ],
        'orange' => [
            'highlightParentText' => 'text-orange-600 dark:text-orange-400 font-bold',
            'highlightParentStandard' => 'bg-orange-200/60 dark:bg-orange-700/40 text-orange-700 dark:text-orange-300',
            'highlightChildText' => 'text-orange-500 dark:text-orange-400',
            'highlightChildStandard' => 'bg-orange-100/60 dark:bg-orange-800/40 text-orange-800 dark:text-orange-200',
            'hoverText' => 'hover:text-orange-500 dark:hover:text-orange-300',
            'hoverTextChild' => 'hover:text-orange-500 dark:hover:text-orange-300',
            'itemClassStandard' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition hover:bg-orange-200/40 dark:hover:bg-orange-600/30',
            'itemClassText' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition',
            'childItemClassStandard' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3 hover:bg-orange-100/40 dark:hover:bg-orange-800/30',
            'childItemClassText' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3',
            'childBorderClass' => 'border-l border-orange-500 dark:border-orange-400',
        ],
        'teal' => [
            'highlightParentText' => 'text-teal-600 dark:text-teal-400 font-bold',
            'highlightParentStandard' => 'bg-teal-200/60 dark:bg-teal-700/40 text-teal-700 dark:text-teal-300',
            'highlightChildText' => 'text-teal-500 dark:text-teal-400',
            'highlightChildStandard' => 'bg-teal-100/60 dark:bg-teal-800/40 text-teal-800 dark:text-teal-200',
            'hoverText' => 'hover:text-teal-500 dark:hover:text-teal-300',
            'hoverTextChild' => 'hover:text-teal-500 dark:hover:text-teal-300',
            'itemClassStandard' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition hover:bg-teal-200/40 dark:hover:bg-teal-600/30',
            'itemClassText' => 'flex items-center gap-3 px-3 py-2 rounded-lg text-gray-700 dark:text-gray-300 font-medium transition',
            'childItemClassStandard' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3 hover:bg-teal-100/40 dark:hover:bg-teal-800/30',
            'childItemClassText' => 'flex items-center gap-3 px-3 py-2 text-sm rounded-lg text-gray-700 dark:text-gray-200 font-medium transition pl-3',
            'childBorderClass' => 'border-l border-teal-500 dark:border-teal-400',
        ],
    ]
];
