<?php

return [
    'colors' => [
        'beartropy' => [
            'main' => 'relative bg-white dark:bg-gray-900/50 text-gray-800 dark:text-gray-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-gray-300 dark:border-gray-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-gray-700 dark:text-gray-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-gray-800 dark:text-gray-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'red' => [
            'main' => 'relative bg-white dark:bg-red-900/50 text-red-800 dark:text-red-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-red-300 dark:border-red-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-red-700 dark:text-red-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'red-textarea w-full border-none !outline-none bg-transparent py-2 text-red-800 dark:text-red-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'blue' => [
            'main' => 'relative bg-white dark:bg-blue-900/50 text-blue-800 dark:text-blue-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-blue-300 dark:border-blue-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-blue-700 dark:text-blue-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'blue-textarea w-full border-none !outline-none bg-transparent py-2 text-blue-800 dark:text-blue-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'green' => [
            'main' => 'relative bg-white dark:bg-green-900/50 text-green-800 dark:text-green-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-green-300 dark:border-green-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-green-700 dark:text-green-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'green-textarea w-full border-none !outline-none bg-transparent py-2 text-green-800 dark:text-green-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'yellow' => [
            'main' => 'relative bg-white dark:bg-yellow-900/50 text-yellow-800 dark:text-yellow-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-yellow-300 dark:border-yellow-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-yellow-700 dark:text-yellow-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'yellow-textarea w-full border-none !outline-none bg-transparent py-2 text-yellow-800 dark:text-yellow-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'purple' => [
            'main' => 'relative bg-white dark:bg-purple-900/50 text-purple-800 dark:text-purple-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-purple-300 dark:border-purple-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-purple-700 dark:text-purple-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'purple-textarea w-full border-none !outline-none bg-transparent py-2 text-purple-800 dark:text-purple-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'pink' => [
            'main' => 'relative bg-white dark:bg-pink-900/50 text-pink-800 dark:text-pink-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-pink-300 dark:border-pink-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-pink-700 dark:text-pink-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'pink-textarea w-full border-none !outline-none bg-transparent py-2 text-pink-800 dark:text-pink-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'gray' => [
            'main' => 'relative bg-white dark:bg-gray-900/50 text-gray-800 dark:text-gray-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-gray-300 dark:border-gray-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-gray-700 dark:text-gray-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'gray-textarea w-full border-none !outline-none bg-transparent py-2 text-gray-800 dark:text-gray-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'orange' => [
            'main' => 'relative bg-white dark:bg-orange-900/50 text-orange-800 dark:text-orange-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-orange-300 dark:border-orange-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-orange-700 dark:text-orange-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'orange-textarea w-full border-none !outline-none bg-transparent py-2 text-orange-800 dark:text-orange-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'amber' => [
            'main' => 'relative bg-white dark:bg-amber-900/50 text-amber-800 dark:text-amber-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-amber-300 dark:border-amber-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-amber-700 dark:text-amber-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'amber-textarea w-full border-none !outline-none bg-transparent py-2 text-amber-800 dark:text-amber-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'lime' => [
            'main' => 'relative bg-white dark:bg-lime-900/50 text-lime-800 dark:text-lime-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-lime-300 dark:border-lime-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-lime-700 dark:text-lime-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'lime-textarea w-full border-none !outline-none bg-transparent py-2 text-lime-800 dark:text-lime-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'emerald' => [
            'main' => 'relative bg-white dark:bg-emerald-900/50 text-emerald-800 dark:text-emerald-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-emerald-300 dark:border-emerald-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-emerald-700 dark:text-emerald-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'emerald-textarea w-full border-none !outline-none bg-transparent py-2 text-emerald-800 dark:text-emerald-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'teal' => [
            'main' => 'relative bg-white dark:bg-teal-900/50 text-teal-800 dark:text-teal-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-teal-300 dark:border-teal-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-teal-700 dark:text-teal-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'teal-textarea w-full border-none !outline-none bg-transparent py-2 text-teal-800 dark:text-teal-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'cyan' => [
            'main' => 'relative bg-white dark:bg-cyan-900/50 text-cyan-800 dark:text-cyan-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-cyan-300 dark:border-cyan-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-cyan-700 dark:text-cyan-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'cyan-textarea w-full border-none !outline-none bg-transparent py-2 text-cyan-800 dark:text-cyan-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'sky' => [
            'main' => 'relative bg-white dark:bg-sky-900/50 text-sky-800 dark:text-sky-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-sky-300 dark:border-sky-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-sky-700 dark:text-sky-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'sky-textarea w-full border-none !outline-none bg-transparent py-2 text-sky-800 dark:text-sky-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'indigo' => [
            'main' => 'relative bg-white dark:bg-indigo-900/50 text-indigo-800 dark:text-indigo-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-indigo-300 dark:border-indigo-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-indigo-700 dark:text-indigo-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'indigo-textarea w-full border-none !outline-none bg-transparent py-2 text-indigo-800 dark:text-indigo-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'violet' => [
            'main' => 'relative bg-white dark:bg-violet-900/50 text-violet-800 dark:text-violet-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-violet-300 dark:border-violet-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-violet-700 dark:text-violet-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'violet-textarea w-full border-none !outline-none bg-transparent py-2 text-violet-800 dark:text-violet-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'rose' => [
            'main' => 'relative bg-white dark:bg-rose-900/50 text-rose-800 dark:text-rose-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-rose-300 dark:border-rose-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-rose-700 dark:text-rose-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'rose-textarea w-full border-none !outline-none bg-transparent py-2 text-rose-800 dark:text-rose-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'fuchsia' => [
            'main' => 'relative bg-white dark:bg-fuchsia-900/50 text-fuchsia-800 dark:text-fuchsia-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-fuchsia-300 dark:border-fuchsia-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-fuchsia-700 dark:text-fuchsia-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'fuchsia-textarea w-full border-none !outline-none bg-transparent py-2 text-fuchsia-800 dark:text-fuchsia-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'slate' => [
            'main' => 'relative bg-white dark:bg-slate-900/50 text-slate-800 dark:text-slate-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-slate-300 dark:border-slate-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-slate-700 dark:text-slate-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'slate-textarea w-full border-none !outline-none bg-transparent py-2 text-slate-800 dark:text-slate-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'stone' => [
            'main' => 'relative bg-white dark:bg-stone-900/50 text-stone-800 dark:text-stone-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-stone-300 dark:border-stone-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-stone-700 dark:text-stone-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'stone-textarea w-full border-none !outline-none bg-transparent py-2 text-stone-800 dark:text-stone-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'zinc' => [
            'main' => 'relative bg-white dark:bg-zinc-900/50 text-zinc-800 dark:text-zinc-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-zinc-300 dark:border-zinc-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-zinc-700 dark:text-zinc-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'zinc-textarea w-full border-none !outline-none bg-transparent py-2 text-zinc-800 dark:text-zinc-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
        'neutral' => [
            'main' => 'relative bg-white dark:bg-neutral-900/50 text-neutral-800 dark:text-neutral-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-neutral-300 dark:border-neutral-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error' => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label' => 'font-semibold text-neutral-700 dark:text-neutral-300/80 text-sm tracking-wide  ml-1',
            'label_error' => 'font-semibold text-red-500 text-sm tracking-wide  ml-1',
            'input' => 'neutral-textarea w-full border-none !outline-none bg-transparent py-2 text-neutral-800 dark:text-neutral-100 min-h-[2.5rem]',
            'help' => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error' => 'text-xs mt-1 text-red-500',
        ],
    ],
];
