<?php

return [
    'colors' => [
        'beartropy' => [
            'main'           => 'relative bg-white dark:bg-gray-900/50 text-gray-800 dark:text-gray-100 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-gray-300 dark:border-gray-700 focus-within:ring-blue-400 dark:focus-within:ring-blue-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-gray-800 dark:text-gray-300 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-gray-800 dark:text-gray-100 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'neutral' => [
            'main'           => 'relative bg-neutral-50 dark:bg-neutral-800 text-neutral-700 dark:text-neutral-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-neutral-400 dark:border-neutral-600 focus-within:ring-neutral-300 dark:focus-within:ring-neutral-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-neutral-700 dark:text-neutral-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-neutral-700 dark:text-neutral-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-neutral-400 dark:text-neutral-500',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'red' => [
            'main'           => 'relative bg-red-50 dark:bg-red-900/20 text-red-900 dark:text-red-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-red-400 dark:border-red-700 focus-within:ring-red-300 dark:focus-within:ring-red-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-red-800 dark:text-red-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-red-900 dark:text-red-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-red-700 dark:text-red-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'orange' => [
            'main'           => 'relative bg-orange-50 dark:bg-orange-900/20 text-orange-900 dark:text-orange-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-orange-400 dark:border-orange-700 focus-within:ring-orange-300 dark:focus-within:ring-orange-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-orange-800 dark:text-orange-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-orange-900 dark:text-orange-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-orange-700 dark:text-orange-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'amber' => [
            'main'           => 'relative bg-amber-50 dark:bg-amber-900/20 text-amber-900 dark:text-amber-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-amber-400 dark:border-amber-700 focus-within:ring-amber-300 dark:focus-within:ring-amber-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-amber-800 dark:text-amber-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-amber-900 dark:text-amber-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-amber-700 dark:text-amber-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'yellow' => [
            'main'           => 'relative bg-yellow-50 dark:bg-yellow-900/20 text-yellow-900 dark:text-yellow-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-yellow-400 dark:border-yellow-700 focus-within:ring-yellow-300 dark:focus-within:ring-yellow-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-yellow-800 dark:text-yellow-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-yellow-900 dark:text-yellow-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-yellow-700 dark:text-yellow-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'lime' => [
            'main'           => 'relative bg-lime-50 dark:bg-lime-900/20 text-lime-900 dark:text-lime-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-lime-400 dark:border-lime-700 focus-within:ring-lime-300 dark:focus-within:ring-lime-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-lime-800 dark:text-lime-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-lime-900 dark:text-lime-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-lime-700 dark:text-lime-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'green' => [
            'main'           => 'relative bg-green-50 dark:bg-green-500/10 text-green-900 dark:text-green-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-green-400 dark:border-green-700 focus-within:ring-green-300 dark:focus-within:ring-green-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-green-800 dark:text-green-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-green-900 dark:text-green-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-green-700 dark:text-green-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'emerald' => [
            'main'           => 'relative bg-emerald-50 dark:bg-emerald-900/20 text-emerald-900 dark:text-emerald-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-emerald-400 dark:border-emerald-700 focus-within:ring-emerald-300 dark:focus-within:ring-emerald-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-emerald-800 dark:text-emerald-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-emerald-900 dark:text-emerald-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-emerald-700 dark:text-emerald-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'teal' => [
            'main'           => 'relative bg-teal-50 dark:bg-teal-900/20 text-teal-900 dark:text-teal-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-teal-400 dark:border-teal-700 focus-within:ring-teal-300 dark:focus-within:ring-teal-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-teal-800 dark:text-teal-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-teal-900 dark:text-teal-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-teal-700 dark:text-teal-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'cyan' => [
            'main'           => 'relative bg-cyan-50 dark:bg-cyan-900/20 text-cyan-900 dark:text-cyan-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-cyan-400 dark:border-cyan-700 focus-within:ring-cyan-300 dark:focus-within:ring-cyan-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-cyan-800 dark:text-cyan-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-cyan-900 dark:text-cyan-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-cyan-700 dark:text-cyan-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'sky' => [
            'main'           => 'relative bg-sky-50 dark:bg-sky-900/20 text-sky-900 dark:text-sky-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-sky-400 dark:border-sky-700 focus-within:ring-sky-300 dark:focus-within:ring-sky-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-sky-800 dark:text-sky-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-sky-900 dark:text-sky-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-sky-700 dark:text-sky-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'blue' => [
            'main'           => 'relative bg-blue-50 dark:bg-blue-900/20 text-blue-900 dark:text-blue-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-blue-400 dark:border-blue-700 focus-within:ring-blue-300 dark:focus-within:ring-blue-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-blue-800 dark:text-blue-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-blue-900 dark:text-blue-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-blue-700 dark:text-blue-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'indigo' => [
            'main'           => 'relative bg-indigo-50 dark:bg-indigo-900/20 text-indigo-900 dark:text-indigo-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-indigo-400 dark:border-indigo-700 focus-within:ring-indigo-300 dark:focus-within:ring-indigo-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-indigo-800 dark:text-indigo-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-indigo-900 dark:text-indigo-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-indigo-700 dark:text-indigo-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'violet' => [
            'main'           => 'relative bg-violet-50 dark:bg-violet-900/20 text-violet-900 dark:text-violet-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-violet-400 dark:border-violet-700 focus-within:ring-violet-300 dark:focus-within:ring-violet-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-violet-800 dark:text-violet-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-violet-900 dark:text-violet-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-violet-700 dark:text-violet-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'purple' => [
            'main'           => 'relative bg-purple-50 dark:bg-purple-900/20 text-purple-900 dark:text-purple-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-purple-400 dark:border-purple-700 focus-within:ring-purple-300 dark:focus-within:ring-purple-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-purple-800 dark:text-purple-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-purple-900 dark:text-purple-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-purple-700 dark:text-purple-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'pink' => [
            'main'           => 'relative bg-pink-50 dark:bg-pink-900/20 text-pink-900 dark:text-pink-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-pink-400 dark:border-pink-700 focus-within:ring-pink-300 dark:focus-within:ring-pink-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-pink-800 dark:text-pink-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-pink-900 dark:text-pink-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-pink-700 dark:text-pink-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
        'rose' => [
            'main'           => 'relative bg-rose-50 dark:bg-rose-900/20 text-rose-900 dark:text-rose-200 border rounded-md shadow-sm focus-within:ring-2 transition',
            'border_default' => 'border-rose-400 dark:border-rose-700 focus-within:ring-rose-300 dark:focus-within:ring-rose-500',
            'border_error'   => 'border-red-500 ring-red-200 dark:ring-red-900',
            'label'          => 'text-rose-800 dark:text-rose-200 -mb-0.5 ml-1 text-[15px] font-semibold',
            'label_error'    => 'text-red-500 dark:text-red-400',
            'input'          => 'beartropy-textarea w-full border-none !outline-none bg-transparent py-2 text-rose-900 dark:text-rose-200 min-h-[2.5rem]',
            'help'           => 'text-xs mt-1 text-rose-700 dark:text-rose-300',
            'error'          => 'text-xs mt-1 text-red-500',
        ],
    ]
];
